### ISSUE TITLE
React-native project importing buffer ^5.1.0 doesn't work on iOS

### ISSUE THREAD

**Issue by silence-may** [bitcoinjs/bitcoinjs-lib#1079]
excuse me 
       my buffer version is 5.1.0   but it does't work on  ios  yet!!
      should i do any more things??
![image](https://user-images.githubusercontent.com/20940285/40267069-02e14e18-5b89-11e8-869f-ed02fa951f0c.png)

**Comment by dabura667** [comment]
What do you mean "doesn't work"?

Please be specific in your questions. Refrain from using "!" and getting upset, and remember that not everyone looking at this issue is watching all your past issues. You NEED to say "this is for a react-native project using xyz for webpack with abc plugins and ..." so that people reading your issues will be able to help you.

Ask in Chinese if you need to. It's better than saying "THIS DOESN'T WORK. TELL ME HOW TO MAKE IT WORK!!!" and getting no answer.

Show us error messages, show us your code, show us anything that can help.

Otherwise everyone will ignore you.

**Comment by dcousens** [comment]
Maybe related to https://github.com/bitcoinjs/bitcoinjs-lib/issues/976

**Comment by silence-may** [comment]
@dabura667 ，谢谢你的建议，我以后会改进我提问题的方式。

**Comment by dcousens** [comment]
Translation?

**Comment by dcousens** [comment]
Can I close?  Was #976 helpful?
