### ISSUE TITLE
Make a compiled version of this library available from somewhere

### ISSUE THREAD

**Issue by davidapple** [bitcoinjs/bitcoinjs-lib#1220]
Please make a compiled version of bitcoinjs-lib v4.0.2 available from somewhere. Even if it's from another repository. Nearly all other js libraries include a dist folder with a minified version of the library pre-compiled. It's standard and saves a huge amount of time. People understand the security risks.

@dcousens mentioned that this library requires Buffer. It is possible to compile, minify and use Buffer purely in the front end.

As much as I hate Bitcoin Cash; they have a developed bitcoinjs-lib into bitcoincashjs and this works perfectly fine purely in the front end. It would be a real shame to see Bitcoin Cash development superseded Bitcoin development because the developers are too stubborn to compile their library for average Joe developers.

I suggest using a checksum to ensure that the minified version is legit.

This issue is a continuation of #314 and #252

**Comment by junderw** [comment]
> People understand the security risks.

I really think they don't.

> I suggest using a checksum to ensure that the minified version is legit.

Checksums don't ensure minified versions are legitimate.

They ensure data integrity against the checksum, so it moves the question from "Is the JS legitimate?" to "Is the checksum legitimate?" If you check the checksum and assume "this must be legitimate because this is the hash on Github" then your definition of legitimate must be "anything that any committer of bitcoinjs or any admin of Github could possibly post" in order to encompass it.

When you use the min js you are placing a lot of trust in the bitcoincashjs and Github. Not only that, but any users of your app will have to trust bitcoincashjs immensely.

**Comment by dcousens** [comment]
> It would be a real shame to see Bitcoin Cash development superseded Bitcoin development because the developers are too stubborn to compile their library for average Joe developers.

:rofl: 

I don't think this is going to go anywhere,  its a discussion we've been at lengths with in https://github.com/bitcoinjs/bitcoinjs-lib/issues/314

https://github.com/bitcoinjs/bitcoinjs-lib/issues/314#issuecomment-63406942
> The conclusion that keeps surfacing is that we're developing financial applications here; as such, we must take the extra precautions to ensure that our applications work as expected and don't contain any malware. I truly believe that this is an important principle to stick to.

Is `npm` any better?
Nearly.  But at least you can trivially diff it against the `git` repository (assuming you audit that).

JS and Bitcoin is already the epitome of bad ideas that made it to production out of necessity,  lets not make it worse by blindly trusting the publishers.

Review your dependencies.

Trust, **but verify.**

**Comment by dcousens** [comment]
Maybe related https://github.com/bitcoinjs/bitcoinjs-lib/issues/886

**Comment by davidapple** [comment]
So what is your view on [BitcoinCash.js](https://bitcoincashjs.github.io/) including compiled versions of their library and promoting the use of it without verification?

I was able to use this library to build a fully operational wallet. I don't know anyone that's had a problem with it.

My point is that the skills required to fix broken dependencies and resolve errors in node is a completely different skill set to developing a functional, secure bitcoin application. So by forcing everyone to install a load of dependencies and resolve errors, you're alienating a huge group of competent developers.

Is somebody able to create a compiled and minified version of this library and share it via another channel please?

**Comment by dabura667** [comment]
> My point is that the skills required to fix broken dependencies and resolve errors in node is a completely different skill set to developing a functional, secure bitcoin application.

Umm, yes those are exactly the skills required to make a secure bitcoin application.

1. The skills to verify the code you are adding as a dependency to your app.
2. The skills to verify the code that converts your code and your dependency's code into a minified blob.
3. The skills to use that tool (which you verified yourself) to actually minify the JS into a blob.

These are the minimum skills you need to even start making a secure bitcoin application.

What you are talking about is a "functional bitcoin application..." an app with copy pasted non-verified code all over it is not secure in any way shape or form.

**Comment by dabura667** [comment]
That said, you can trust if you want.

But PLEASE let your users know "I am using xyz without verification, so you, as a user of my app, must not only trust me, but also the maintainers of the dependencies I am using" in some sort of disclaimer.

This is a good read to keep you up at night:
https://hackernoon.com/im-harvesting-credit-card-numbers-and-passwords-from-your-site-here-s-how-9a8cb347c5b5

**Comment by davidapple** [comment]
At very least, the bitcoinjs-lib readme could be developed to include clear Browserify instructions. At the moment it simply says "Use Browserify" without giving useful commands to run.

**Comment by dcousens** [comment]
@davidapple because modules are the best and worst parts of modern JS.  It is part of the ecosystem,  and you need to get your head around it if you want to build modern JS applications.

If so be it you want to use JS as directly as a drop in `script src=` and hope for the best,  go for it!
Browserify `bitcoinjs-lib` into a standalone script,  and get going.

But that is your choice,  and it isn't a simple one.  Nor is it compatible in many scenarios,  as we use modern ECMAScript features (`let`, `const`) which have undefined or poorly defined behaviour in older browsers.

You might want to look into using something like `babel`, or `webpack`,  but beware,  it is a minefield,  and yes you need to know about it.

Bitcoin is an additional minefield where mistakes in these decisions lead to **fund loss**,  of peoples money (which by the way,  they care about!).

**Comment by davidapple** [comment]
> They ensure data integrity against the checksum, so it moves the question from "Is the JS legitimate?" to "Is the checksum legitimate?" If you check the checksum and assume "this must be legitimate because this is the hash on Github" then your definition of legitimate must be "anything that any committer of bitcoinjs or any admin of Github could possibly post" in order to encompass it.

I don't really see how trusting bitcoinjs and Github is any worse than trusting 44 other repositories and Github. By using so many dependencies, are you not adding more opportunities for bad actors to inject malicious code?

Would it not be better to publicly announce an official bitcoinjs bitcoin donation address across multiple social media platforms and then sign a message (the message could be the minified version of the file) with the private key? Again, you don't have to publish it on this repository, you could publish it anywhere on the web and people could verify that you have signed it. This way we only have to trust one entity bitcoinjs.

**Comment by xloem** [comment]
I hadn't found this fork and made a separate repository at https://github.com/xloem/bitcoinjs-lib-browser .  Instead of a fork, it includes this as a dependency.
