### ISSUE TITLE
Question on base58 & bitcoin addresses

### ISSUE THREAD

**Issue by reardenlife** [bitcoinjs/bitcoinjs-lib#1374]
I am not sure if this is the right place for the question, but I will try.

I cannot figure out why base58 encoded p2sh addresses have prefixes from 31 to 3R ( see https://bitcointalk.org/index.php?topic=5126151.msg50433041#msg50433041 ).  The calculation shows that if base256-to-base58 conversion is applied from the first byte of the binary data structure [version][20-byte-hash][checksum] and the first byte is static, then that first byte will affect the range of second character in base58 encoding. I've got the range of 25 symbols (log2(25)=4.64 bits), which is far more than it should be: log2(58)-(8-log2(58))=3.72 bits.

Am I missing something?

**Comment by junderw** [comment]
You're overthinking.

We don't convert bits directly since 58 is not a multiple of 2.

Instead, we convert it to a decimal number and encode that number into base58 by divide then mod method.

The question you are asking is akin to: "why does my base64 encoded data change two characters when I'm only changing the last 6 bits of my data?"

The answer is the same:

because positionally, the bitlengths of each character doesn't line up, causing overflow into the adjacent character sometimes.

Also, I'm looking at your thread.

Don't store addresses in the database, base58 decode and search by the first byte. Problem solved.
