### ISSUE TITLE
Add TurtleCoin to a bitcoinjs-lib project, what the network parameters would be

### ISSUE THREAD

**Issue by mcfang** [bitcoinjs/bitcoinjs-lib#1390]
Does anyone know what the network parameters would be for TurtleCoin? For example the network parameters for BTC are as follows: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/networks.js
I'm trying to add TurtleCoin to a bitcoinjs-lib project.

**Comment by junderw** [comment]
Ask them: https://github.com/turtlecoin/turtlecoin

There is a possibility that this library is not compatible.

But in order to figure that out, someone who knows a lot about us needs to do research about TurtleCoin, OR someone who knows a lot about TurtleCoin needs to do research about us.

I will not research TurtleCoin, so please ask them to research us. (Though they might be familiar with our API, and might be able to tell you right away)

I don't know anything about TurtleCoin, by the way.

**Comment by zeroingstart** [comment]
。。

**Comment by mcfang** [comment]
Thanks junderw. I also add a issue at TurtleCoin github.
