### ISSUE TITLE
[Help] I think my BTC was stolen

### ISSUE THREAD

**Issue by idoor88** [bitcoinjs/bitcoinjs-lib#1413]
Hi all,
I am using this library and built a wallet to send and receive BTC, I am using this version:
"bitcoinjs-lib": "^5.0.3",
and some code related to private key as following:
```js
const keyPair = bitcoin.ECPair.fromWIF(fromPrivateKey);
const txb = new bitcoin.TransactionBuilder();
........
unspentList.forEach((unspent, index) => {
  txb.sign(index, keyPair);
});
const txhash = txb.build().toHex();
.........
```
Somehow, when I used https://insight.bitpay.com/api/tx/send api to send the signed transaction of around $2 of BTC to my coinbase account, I expected only one transaction, but actually three transactions happened, and none of the 3 transactions sent to coinbase, and all my BTC of worth $10 are gone, so I am not sure if the bitcoin library was sending my private key somewhere and stolen my BTC from my wallet?
Would somebody please explain what was going on?
here is the link for the transactions on May 22:
https://www.blockchain.com/btc/address/1PHTygJ8ba6oA3EkRiRA9BvErxPE9bVMAQ

Thanks

**Comment by junderw** [comment]
1. This library doesn't send private keys anywhere.
2. However, once you `npm install` and the code is in your node_modules folder anyone can modify it. (a virus, a roommate, etc.)
3. Also, your private key could have been stolen from somewhere else. (it was stored insecurely etc.)

You linked to an address. Who's address is this? Yours? Coinbase's? Someone else's?

**Comment by idoor88** [comment]
The linked address: https://www.blockchain.com/btc/address/1PHTygJ8ba6oA3EkRiRA9BvErxPE9bVMAQ is my wallet address, on May 22nd, I sent about $2 worth of BTC to my coinbase wallet, you can see from the link, there are three transactions happened, and my $10 worth of BTC (I only had that much) was gone right after the three transactions went through, my private key is on my local phone device, nobody stolen there, I am not sure if somebody put code in the library (back door) and sent my private key away from my device, I have not checked the code in node_modules yet. but this same problem happened to my friend as well, when he used the wallet to send BTC, also lost $30 worth of BTC, so I am scared of this and not sure what should I do now, has anybody have the same problem before with this library?
Thanks

**Comment by junderw** [comment]
The address has 12 transactions. 4 are for BTC, and 8 are for Tether (USDT).

Tether transactions can be seen here: https://omniexplorer.info/address/1PHTygJ8ba6oA3EkRiRA9BvErxPE9bVMAQ

```
01. Someone sent $2.90 in BTC to it.
02. Someone sent $1.00 Tether USD (USDT) and $0.04 in BTC to it.

03. It sent $0.50 USDT to 3LeQhy54gmAboVG1jqJGiKPzWPehCqNo6J. With $0.08 fees paid in BTC.
04. It sent $0.10 USDT to 3LeQhy54gmAboVG1jqJGiKPzWPehCqNo6J. With $0.07 fees paid in BTC.
05. It sent $0.10 USDT to 3LeQhy54gmAboVG1jqJGiKPzWPehCqNo6J. With $0.07 fees paid in BTC.
06. It sent $0.10 USDT to 3LeQhy54gmAboVG1jqJGiKPzWPehCqNo6J. With $0.07 fees paid in BTC.
07. It sent $0.10 USDT to 1NcpBHAw4wadqDvi6p7JUFLXKa8FUqeZ8q. With $0.07 fees paid in BTC.
08. It sent $0.10 USDT to 1NcpBHAw4wadqDvi6p7JUFLXKa8FUqeZ8q. With $0.07 fees paid in BTC.
09. It sent $0.38 in BTC to 1ENjcYmApVQzjunJ3CqZRYqrgdcfEoP176. With $0.06 fees paid in BTC.
10. It sent $1.26 in BTC to 19sHnSrHSaVNMZ7arr6r67eJXL6Ns3aiMx. With $0.56 fees paid in BTC.

11. Someone sent $50.00 USDT and $0.04 in BTC to it.
12. Someone sent $9.95 in BTC to it.
```

May 22nd is 7,8,9,10 in the list above, but those 3 transactions aren't sending $10 of bitcoin... only $0.20 of USDT and $1.64 of BTC, along with paying $0.76 in bitcoin fees.

At no point has this address sent $10...

Could you please clarify what these transactions were to / from?

It sounds like you are probably reading the block explorer's information incorrectly or making a misunderstanding. I would like to help you understand, so please give me some more information.

**Comment by junderw** [comment]
Right now that address has $50 in USDT and $10 in BTC on it currently.

**Comment by idoor88** [comment]
Hi Junderw, thanks for your response, I am talking about on May 22nd, I sent one transaction of BTC from my wallet address 1PHTygJ8ba6oA3EkRiRA9BvErxPE9bVMAQ to my coinbase wallet: 3NEAswvkD3MUd947owYyNXvUwCb2DXPzfp, but on that day it triggered totally 4 sending actions from  my wallet 1PHTygJ8ba6oA3EkRiRA9BvErxPE9bVMAQ to three different receiving addresses, see it from here: https://www.blockchain.com/btc/address/1PHTygJ8ba6oA3EkRiRA9BvErxPE9bVMAQ
also I attached this screenshots, and also my coinbase receiving wallet address: 3NEAswvkD3MUd947owYyNXvUwCb2DXPzfp is not one of the receiving address in the 4 sending transactions,  I checked my coinbase account, I did receive some BTC on that day with one transaction as receiving.
![Screen Shot 2019-06-10 at 11 22 24 AM](https://user-images.githubusercontent.com/27703710/59207561-46fe0d80-8b75-11e9-98e0-2ce6f7dcc697.png)
<img width="896" alt="Screen Shot 2019-06-10 at 11 33 40 AM" src="https://user-images.githubusercontent.com/27703710/59207608-5bdaa100-8b75-11e9-84a4-6094e42f5b95.png">

**Comment by junderw** [comment]
Unfortunately, there doesn't seem to be anything else I could do.

If you can find some sort of bug, I'd be glad to fix it.

Also, if there was malware in our library, you would definitely hear of more issues brought up here. This library is downloaded 20000 times a week. If we were the source of some malware, I'm sure this Github would be filled with tons of non-bot-like real people with reports of similar issues.

This leads me to believe that the source of any malware (though I'm not fully sure if what you are experiencing is malware) is somewhere else in your app's build chain.

Every tool, every webpacker, every plugin has the ability to inject malicious code into your app.

Since there are not a ton of people reporting the same issue, I would try looking at the libraries and tools that are not widely used, or maybe one of your internal devs created.

But on second thought, why would someone with private key stealing malware steal only $10? Why not wait until you put more money on it?

This is what leads me to believe that perhaps you are being tricked, and that is not really your address.

Anyway. The best bet would be to zip up the whole folder of the project with everything installed and have someone investigate all the source code of your dependency tree.

Please reopen if you find an issue with the library we can fix.

I hope you get your $10 back.
