### ISSUE TITLE
BTC sent to my wallet was immediately transferred away

### ISSUE THREAD

**Issue by idoor88** [bitcoinjs/bitcoinjs-lib#1418]
After I created a wallet for BTC with this library (5.0.3), the address is 1J9xVfqvdzk8CJhP86GYa45DxGDHBBdXLh, then I sent $5 worth of BTC from my coinbase account, but when the BTC got to my wallet address 1J9xVfqvdzk8CJhP86GYa45DxGDHBBdXLh, it was immediately transferred to another address, as indicated here:
https://www.blockchain.com/btc/address/1J9xVfqvdzk8CJhP86GYa45DxGDHBBdXLh

 here is the code to create the wallet:
```js
const hash = // DANGEROUS: single sha256 of the username
keyPair = Bitcoin.ECPair.fromPrivateKey(hash);
const addr = Bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey }).address;
const secret = keyPair.toWIF();
return {
  publicKey: addr,
  privateKey: secret,
};
```

**Comment by junderw** [comment]
Can you give me an example of what a `username` might look like?

Can the user choose their own username?

Are usernames like `jonnyboy123` or are they like a long user ID like `6f2jhd5ua5NFtoB4y3uK` ?

The reason your coins were stolen is because the hash of a username should NEVER be used as a private key.

There are bots that generate hashes of common words / password lists etc. and will steal any coins on them.

To learn why this is a bad idea, look at this:

https://bitcoin.stackexchange.com/questions/41618/why-are-brain-wallets-not-secure-people-keep-saying-it-but-explain-to-me-why

"brain wallets" were a thing similar to what you are doing, except they use a password hash instead of a username hash.

**Comment by idoor88** [comment]
Got it, thanks
