### ISSUE TITLE
Creating deterministic private key with sha256, what kind of object is that? (NodeJS/NPM noob)

### ISSUE THREAD

**Issue by Mr-Mondragon** [bitcoinjs/bitcoinjs-lib#1451]
I'm trying to play around with bitcoin-js, but being rather new to Node / NPM I find myself a bit lost in trying to sort out what is what. 
For example, something that I think ought to be very simple, I deterministically create a private key like this:

    const privateKey = bitcoin.crypto.sha256("My Secret Passphrase");

Now I have no idea what kind of object `privateKey` actually is. By trial and error I found out I can create a ECPair from this like:

    const keyPair = bitcoin.ECPair.fromPrivateKey(privateKey);

But how or where do I find out what methods or functions there are on an object like privateKey? For example if I want to print its hex representation, where do I look if and how this is possible?

I understand my privateKey object is some kind of buffer, but how would I go about doing the same if I have a hexadecimal string as input? (of length 64, i.e. 256 bits)

**Comment by Mr-Mondragon** [comment]
Upon further trial and error, I found out I can create a privateKey buffer from a hexadecimal string like so:

    // the sha256 hash of 'My Secret Passphrase'
    const s = '6811824db7308870be81c8d7319d91b526aaff6fb8223ba341b52efd254eea66';
    const privateKey = Buffer(s,'hex');

Of if I create a sha256 hash I can output its hex representation like this:

    const privateKey = bitcoin.crypto.sha256("My Secret Passphrase");
    console.log(privateKey.toString('hex'));

But I more or less stumbled upon this by accident (copied from some random tests).

How or where can I find the syntax or documentation or the available types and methods for objects like these?

**Comment by junderw** [comment]
First of all:

**NEVER, EVER, EVER, EVER USE A STRING THAT WAS INPUT BY A USER TO CREATE A PRIVATE KEY**

Yes, there used to be popular things that did stuff like that and threw the input into reeeally long hashes that take 20 seconds to hash in the browser so "oh boy that means my private key is really secure"... no it doesn't.

---

Now on to your question:

1. Primitives: String, Number, Boolean, Null, Undefined... these are well documented and have been with JavaScript since the beginning. Google them.
2. Anything else is an Object type. Object types are defined in libraries, and Node JS comes with various standard libraries documented here: https://nodejs.org/docs/latest-v10.x/api/documentation.html the type you discovered is `Buffer` (which you will see a tab for Buffer on the documentation site I linked above)
3. For types in the Bitcoinjs-lib library, you can learn about what the objects do by looking at the source code. Currently the `ts_src` folder contains all the human readable source code and the `src` folder is just being tracked on git because reasons (it's a long story)

---

Here's a tip: look at the test folder to see examples of every object defined in our library being used in many ways. Especially the integration tests, which will show many ways to use the library to actually create transactions etc.

**Comment by Mr-Mondragon** [comment]
Thanks a lot! 👍

And yes I fully understand (and agree) on never using human input to generate private keys, or using some fancy expensive hash and thinking it adds any security. 
Was just an example here, in practice I'm using long cryptographically secure entropy strings. 

Will look into Node and Javascript primitives and Bitcoinjs tests for reference. Thx again.
