### ISSUE TITLE
Find network from address

### ISSUE THREAD

**Issue by monokh** [bitcoinjs/bitcoinjs-lib#1459]
Given an address only, is it possible to retrieve the network? I understand that addresses have checksums and then it's possible do some matching with the `bech32`, `scripthash` and `pubkeyhash` prefixes to figure it out but would be nice to have this from the library.

Perhaps `bitcoin.address.fromXXXX` functions can also return a network name if it is detected?

```
> b.address.fromBase58Check('mimbxkaz5V5kjpHUmLTjz8tNo88a5AebYx')
> {version: 111, hash: Uint8Array(20), network: 'testnet'}
```

**Comment by junderw** [comment]
If you must read the network implicitly from an address, your app is insecure and you should reconsider your design.

A user should always explicitly choose their network. If your app only has one currency, make that network a constant. If it has multiple currencies, make the user select from a list and add them all as constants.

**Comment by monokh** [comment]
> If you must read the network implicitly from an address, your app is insecure and you should reconsider your design.

If my understanding of addresses are correct, isn't the network of an address very explicit via the prefix?

I'm not sure it's in the remit of the library to decide what an application does with its outputs. As long as there is no security concern of the feature itself i.e. determining the network of an address is deterministic.

I'm working on an integration where the only thing I have access to are addresses. I have the need to derive which network these addresses belong to. I will be doing this regardless of support within `bitcoinjs-lib` because there really is no other option. 

Please help me understand, say there is an app where you paste an address and it will tell you which bitcoin network this address belongs to. Where is the security issue in this?

**Comment by junderw** [comment]
Example:

Litecoin P2SH address

Monacoin P2PKH address

the above two have the exact same address version and format.

If a user sends Litecoin to the Monacoin address, they are sending a P2SH output (in other words they are sending to a script hash) whereas the hash in the Mona address is a pubkey hash.

This effectively makes sending the wrong coin into "sending your coin into a black hole with 0% chance of recovery"

If your app was presented with such an address you would have to tell the user "ok, so your address is either a LTC P2SH or a MONA P2PKH, and be careful to not mix them up or else you lose money."

So as I said before. The user must make an explicit decision on which coin they want to use.

if your app is called "Dogecoin Wallet" then by installing your app the user is explicitly saying "I am using Dogecoin"

if your app is multi-coin, you MUST ask the user explicitly.

I have been working at a multi-currency crypto exchange for years... trust me, if you continue down this path users will lose money.

**Comment by monokh** [comment]
I think you are making too many assumptions about the use case. In my case, it being bitcoin(coin) has already been selected. The only missing info is the network, so there is no issue with deducing it from the address. The bitcoinjs library is used purely for Bitcoin.

I'm unaware of how multi coin support is intended within the library but it would make sense to make it explicit. I'm confused how it's possible to rely on the library for altcoins otherwise, precisely for the reasons you mention. Is this the only scenario where the coin matters? How about when you derive addresses for payments?  The `networks` enum only gives the impression of Bitcoin support (bitcoin, testnet, regtest).

Perhaps this is highlighting how multi coin support should fit within the library.

**Comment by junderw** [comment]
Even if you restrict the networks to value based mainnet and non-value-based testnet/regtest, the issue still stands.

Your app should not be automatically assuming the meaning of an address and telling the user what their address means.

The user should ALWAYS tell the app specifically which coin they are intending to deposit (etc) and your app should throw an error if they give you an address that does not match the expected network.

Example:

- A user creates a wallet on some dumb multicoin app with a bad UI.
- They grab an address for Flippycoin P2SH
- Flippycoin P2SH has the same address version as Bitcoin P2PKH
- They paste their address into your app
- Your app's auto-detect pops up and says to them "Don't worry, mate. Your address is definitely Bitcoin Mainnet, there's no other thing it could possibly be!"
- The user gets confused, and sends 1000 BTC from your wallet app to that address.
- It is impossible to spend a P2PKH output when the hash cotained is actually the hash of a script, and therefore the user loses money to a black hole.
- Your app helped contribute to the confusion that lead to money loss.

How it should go:

- Your app supports mainnet, testnet, regtest bitcoin networks.
- On boot, the user has to tap one of the three and decide what "mode" they want the app to work in.
- If in mainnet "mode", reject anything that doesn't match mainnet params etc.
- The above user makes the same mistake, but this time, they are confronted with a screen asking "hey, which network are you using? Bitcoin, Bitcoin Testnet, or Bitcoin Regtest" which gives them another opportunity to think "hey, wait a second, this isn't Flippycoin..."

Also, there have been instances in the past where an app supported testnet and mainnet in the same interface and scammers took advantage of this by trying to "sell people bitcoin" and telling them to download the app that supported testnet, sending them testnet coins and walking away with the money because the victim didn't know better and the wallet app UI did not make it apparent to them they weren't getting bitcoin except for a tiny little flask icon in the corner (which doesn't relay "hey, these coins are worthless" to a normal user)

The main point I am getting at:

You are probably making an app with someone like yourself in mind. (That's how most devs make anything in any space, so it's not an insult)

But you have to realize that poor UI / UX decisions for normal non-bitcoin-literate users (Though they may be GREAT UI decisions for a developer working on Bitcoin wallets etc) can be the difference between a user losing money, not losing money, or having a lower chance of losing money, etc.

Multicoin support is extendable through creating your own network objects.

A pretty comprehensive list (and library to convert them to BitcoinJS compatible ones) is here: https://github.com/cryptocoinjs/coininfo

btw, I am not making assumptions on what your app does, I am just giving you examples as to why the "rule of thumb" is to never assume network from address, but rather to explicitly choose a network, then use that network's info to whitelist the allowed address types. And then give examples as to why that rule exists.

If I give someone reasons why they should not stick a fork in an electrical socket and they say "but none of those things apply to me, I'm going to wear rubber gloves and everything" the point still remains that there are valid reasons to not do so. (For example, someone who doesn't know that the rubber gloves are a vital part of doing it safely might look at you doing it and say "oooohhh so it's ok to stick forks in electrical sockets!" and encourage others to do so without mentioning the rubber gloves.)

So even if you somehow managed to figure out every possible problem with assuming network from address and account for and manage them... you still shouldn't do it because it sets a dangerous precedent and will get users used to the idea, making them more prone to disaster when someone else makes an app that isn't as careful as yours.

I hope you understand my reasoning for being adamant about this issue, and I don't seem to overbearing.

If you want to make your own tool, you can, and posting a link here might be helpful to someone else with the same idea as you. But I would highly advise against it.

**Comment by monokh** [comment]
Firstly, I really appreciate you taking the time to lay this out. I've learned a few things here.

From my understanding, deriving the network of a bitcoin (the coin) address is not an assumption but a rule just like any other. For example, given the network and pubkey, you can derive a p2pkh address. What would a library be without the premise of applying these rules? Where this gets confusing is considering the multi coin world. It makes sense if your worry is that the library is used for other coins and therefore providing this feature can be dangerous. No arguments there.

Regarding the use case, an app can do everything right, exactly as you mention (and I'm doing it too) and still end up with the need to validate an address. Having selected bitcoin and bitcoin mainnet, the user pastes in a testnet address. What do we do now? A good UX would notify the user of the mistake immediately, otherwise when will we detect it, when it hits a node?
