### ISSUE TITLE
PSBT inputs from 3PBP

### ISSUE THREAD

**Issue by aquqz2** [bitcoinjs/bitcoinjs-lib#1478]
Since PSBT requires additional nonWitnessUtxo/witnessUtxo data for adding inputs, what would be the most elegant way of acquiring that via a 3PBP?

This is a great lib by the way, thank you for the hard work.

**Comment by junderw** [comment]
witnessUtxo can be created by most blockchain explorers, since it's just the amount of the utxo and the output's scriptPubkey.

smartbit already gives you both those data points ie.

nonWitnessUtxo is just the full raw transaction, so 2 steps: 1. get utxos. 2. for any non-segwit utxos, fetch raw tx from separate API endpoint.

it will take much longer. but it's possible.
