### ISSUE TITLE
Why first element of txinwitness is empty string?

### ISSUE THREAD

**Issue by sjlee1125** [bitcoinjs/bitcoinjs-lib#1521]
I used getrawtransaction of rpc call
and I got result this
```json
"vin": [{
        "txid": "ce257ceb834b608a776792873357c41f7164344ad6dd9a48e1330e7d81770952",
        "vout": 0,
        "scriptSig": {
            "asm": "",
            "hex": ""
        },
        "txinwitness": ["", "3045022100dcad5ab480a52f565894f7fdb2e1e86b63d97d34f7f1d08d2d7bdc74ca4cfb9f0220580cf49aabaf4f986b83eba57fda632949cfcd0206927e32449ca63c35d6b9e001", "512103079fd7069b07f95c9d806723c61ed3e18924ac577f30c2167fec8481470e883251ae"],
        "sequence": 4294967295
    }],
```
the address of input is p2wsh address
that is 1 of 1 p2wsh address
Why first element of txinwitness is empty string?

**Comment by junderw** [comment]
Because there's a bug in OP_CHECKMULTISIG that requires a hardfork to fix... and it's not a major bug, so everyone just adds an empty pushdata (aka OP_0 or OP_FALSE) to get around the bug.

It is a bug in Bitcoin since the beginning, and we are adding that in order to match the bug behavior.

Multisig is secure, though. Don't worry.

**Comment by junderw** [comment]
Read the description of OP_CHECKMULTISIG here https://en.bitcoin.it/wiki/Script
