### ISSUE TITLE
support USDT trading?

### ISSUE THREAD

**Issue by DingGeng-GitHub** [bitcoinjs/bitcoinjs-lib#1532]
"bitcoinjs-lib": "^5.1.7",

Please，does the latest version support USDT trading?

**Comment by junderw** [comment]
Yes, you can send **Omni based** USDT using this library.

Check the examples here, and read the thread until the end.
https://github.com/bitcoinjs/bitcoinjs-lib/issues/1176

Once you figured out how to do it on v4, you can read the integration tests for v5 to do the same for PSBT instead of TransactionBuilder.

**Comment by junderw** [comment]
I rewrote the example given in the thread for v5.1

https://github.com/bitcoinjs/bitcoinjs-lib/issues/1176#issuecomment-574078373
