### ISSUE TITLE
[Coding sample request]I need sample code joining two txs into one (not coinjoin)

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1542]
Hi. 
Let's say 2 friends want to send bitcoins. They decide to join their sending into one trasaction.

I know that this can ben done with SIGHASH_SINGLE | SIGHASH_ANYONECANPAY but I don't have all the details to make it work.

Could it be possible to have an example?

Thanks.

**Comment by junderw** [comment]
it is much simpler to just agree upon the inputs and outputs ahead of time then just sign.

Since the transaction will be broadcasted eventually and you're not worried about privacy.

1. Everyone agrees on inputs and outputs.
2. One person makes the unsigned PSBT, passes it to all signers.
3. All signers sign, then export their signed PSBT and give it to the PSBT maker.
4. PSBT maker combines all signed PSBTs, then finalizes all inputs, extracts the signed transaction, then broadcasts.

**Comment by junderw** [comment]
all steps besides 1 are in the current examples. (I think the first example in transactions integration tests)

**Comment by educob** [comment]
Hi Junderw.
Thanks for the answer.
What you propose takes each user through a several steps process. Besides if one of the users don't finally sign the whole tx is invalid.
I'd like to develop a single step where each user just signs a partial tx and a 2nd user adds more inputs/outputs and finally the tx is sent. In this way it's a one-step process per user and there is no risk of the transaction getting invalid (I think).
thanks.

**Comment by junderw** [comment]
OK, so in order to accomplish this, you need two things:

1. The ability to add inputs without breaking signatures (SIGHASH_ANYONECANPAY) (ACP)
2. The ability to add outputs without breaking signatures (SIGHASH_NONE or SIGHASH_SINGLE)

Problems arise with these sighashes though.

1. ACP | NONE means that any miner that sees the transaction can create a separate transaction with the same input and a different output to steal funds.
2. ACP | SINGLE means that anyone is able to take the change and fees from your input. This would basically require for the final signer to always pay the fee and for each earlier signer to always send the exact amount of the input in their output... Which makes wallet management extremely difficult.

If you were to do it, the last signer should just sign with SIGHASH_ALL as normal, so that there is no funny business done with their ACP | SINGLE signatures by miners etc.

There is no real use case for this. Mike Hearn made a decentralized crowd funding platform called lighthouse using ACP | SIGHASH_ALL... but the wallet had to create extra transactions in order to size the UTXO to the exact donation amount ahead of time... no one used it, and it is now no longer supported.

In general, you want all parties to agree upon all inputs and outputs to make sure no one is trying to cheat someone out of money.

**Comment by educob** [comment]
Thanks.

I'll think about it.

**Comment by tiero** [comment]
> If you were to do it, the last signer should just sign with SIGHASH_ALL as normal, so that there is no funny business done with their ACP | SINGLE signatures by miners etc.

Hi @junderw Let's say we want to do that rn with bitcoinJS, this flow it's safe?

1. Alice creates a PSBT and adds an input with SIGHASH NONE
2. Bob (a coordinator trusted by Alice) gets the PSBT, only adds a couple of outputs and finalize all inputs.
3. Bob Extract the transaction and broadcast.

I'm correct if I say that the `.finalizeAllInputs` would just flag the Alice's Inputs with `SIGHASH_ALL` so no miners could steal the coins?

```js
    const unspentAmount = 1e8
    const txFromAlice = new bitcoin.Psbt({ network: regtest })
      .addInput({
        hash: '71ef7adee71c423398edd92c792dd6045fd8527d10f3c2165d132fe6ece4b4a3',
        index: 1,
        sighashType: bitcoin.Transaction.SIGHASH_NONE,
        witnessUtxo: {
          script: alice.output,
          value: unspentAmount
        }
      })
      .signInput(0, aliceKeyPair, [bitcoin.Transaction.SIGHASH_NONE]);

   // Alice give the tx to Bob 
    const fee = 500
    const bobAmount = 5e7
    const change = unspentAmount - bobAmount - fee
    const txFromBob = bitcoin.Psbt.fromBase64(txFromAlice.toBase64(), { network: regtest })
      .addOutputs([
        {
          address: bob.address,
          value: bobAmount
        },
        {
          address: alice.address,
          value: change
        }
      ])
        
    txFromBob.validateSignaturesOfAllInputs()
    txFromBob.finalizeAllInputs()

    // The resulting tx It is now safe???
```

**Comment by junderw** [comment]
No, that is not safe. I will edit to hide your example so no one will try to copy-paste it.

To make your example safe, Alice would need to add an input of Bob's with SIGHASH_ALL before Alice signs her SIGHASH_NONE input.

That way, Alice's signature covers Bob's input, requiring Bob to sign off on the outputs.

Then when a miner sees the unconfirmed tx, they can't touch any of the outputs because Bob's signature covers them, and they can't re-use Alice's signature, because the signature includes Bob's input, which the miner can not sign for.

If Alice signs for SIGHASH_ANYONECANPAY | SIGHASH_NONE then there is no way Alice could make that safe... Alice's signature literally says "I sign away the rights to the coins in this UTXO and don't care about the other inputs or outputs." so a miner could just copy paste the signature and use it in any transaction.

Your example (SIGHASH_NONE) with only one input at signing says "I approve this input to only be used if it is the only input, but I don't care about the outputs." and unless another signature exists in the tx that has more strict rules, any miner could change the outputs and replace your transaction.

**Comment by tiero** [comment]
> To make your example safe, Alice would need to add an input of Bob's with SIGHASH_ALL before Alice signs her SIGHASH_NONE input.

Thank you so much for your quick response.

So, If I got it right:

1. Alice adds an input owned by Bob flagging it with SIGHASH_ALL
2. Alice now finally adds his input owned by her and signs with SIGHASH_NONE
3. Bob gets the tx and adds an output to himself (Kind of payjoin scheme?)
4. Bob signs his own input with his key, finalizes the tx and broadcast

Thank you in advance.

**Comment by junderw** [comment]
Should be safe.

**Comment by andriibezkorovainyi** [comment]
> Alice adds an input owned by Bob flagging it with SIGHASH_ALL
Alice now finally adds his input owned by her and signs with SIGHASH_NONE
Bob gets the tx and adds an output to himself to get back the bob's input added by Alice (Kind of payjoin scheme?) and the output that spends Alice's input
Bob signs his own input with his key, finalizes the tx and broadcast

Hi @junderw, I've faced a similar situation, but i have many Alices.  Actually I have one wallet and many funded accounts bind to it. What I need is to compute a common input of variety of my accounts outputs, to decrease comission fees. 
How to use this approach to fit these conditions? @tiero , if you have done this, I would appreciate your help too, maybe example?

**Comment by junderw** [comment]
You don't need special sighash flags!

1. Open each account, create a new PSBT and add all the inputs you want. Then export the PSBT.
2. Once you get the input-filled PSBTs from each account, combine them. Then count the total amount and create the output.
3. Send the new PSBT with all accounts inputs and the output(s) to each account's wallet.
4. signAllInputs()
5. Export the signed PSBT from each account, then combine them, finalizeAllInputs(), and extract the transaction and broadcast.

**Comment by andriibezkorovainyi** [comment]
@junderw thank you for quick answer, sir. I'm quite new to btc related development. The node implantation that stores my wallet is [bcoin](https://github.com/bcoin-org/bcoin) does bitcoinjs-lib support it?

**Comment by junderw** [comment]
Looks like bcoin doesn't support PSBTs. https://github.com/bcoin-org/bcoin/pull/607

**Comment by andriibezkorovainyi** [comment]
@junderw thank you for this informations, this probably saved me a lot of time and nerves. So, is that was a single possible solution, maybe there are features to perform something similar in a different way?

**Comment by junderw** [comment]
I don't know much about bcoin, but maybe you can ask them, or figure out a way to get the info you need from your bcoin wallet and use it with BitcoinJS?
