### ISSUE TITLE
Relation around browserified bundles

### ISSUE THREAD

**Issue by xloem** [bitcoinjs/bitcoinjs-lib#1556]
This has been discussed at length #1220 #314 

Please do not advertise any minified js files on this repository.

_Originally posted by @junderw in https://github.com/bitcoinjs/bitcoinjs-lib/issues/965#issuecomment-611800511_

I made the contribution error of linking to a minified bundle of this library.  I see now this discourages the user from verifying the code.

Really, the only reason for publishing things like that is to contribute to the community, so it would be good to relate around what is a contribution and what is harmful.

Using this in a browser, it's helpful to provide to users a way to check the library they are using is the same as the one somebody published, even if that means trusting github a little.

It sounds like it would be much preferable to provide a _non-minified_ browser bundle, but it also sounds like this could be a sore point now, and browser bundles are really to be avoided.

I'd like to at least connect around the idea of publishing _non-minified_ browser bundles, to support the value of sustaining auditability of financial code.  There are at least two repositories offering web bundles of this library out there.  With collaboration and communication, we could find ways to support each others' values and goals.

**Comment by junderw** [comment]
You are missing the point.

Here is a tl;dr of the entire discussion of all the issues so far re:publishing an official bundle.

1. Apps using this library can potentially handle millions of dollars.
2. Therefore devs creating apps with this library MUST verify all the source code that goes into their app.
3. Providing a bundle would encourage developers to use that bundle without verifying it. (Regardless of it being minified or not)
4. Therefore we will not provide a pre-compiled bundle, minified or not. And anyone who promotes a pre-compiled bundle, minified or not, will have their post editted, removed, or otherwise censored to prevent developers from half-heartedly downloading it.
5. Tools like browserify, uglify-es, and others (like webpack) are all open source and available for review and use.
6. If you need a bundle, you should develop the package you need using us as a dependency, then bundle your own js file using a tool that you have verified is not doing anything suspicious. (We support browserify and uglify-es)
7. Other libraries might offer pre-packaged bundles hosted on github etc. but devs should not use them.

Many projects start out as "just messing around" and then evolve into a wallet that stores millions of dollars of people you don't even know.

So unfortunately the response is no. We have no interest in even feigning interest in supporting any official bundle for the community. Each dev must compile their own bundle using the available and widely vetted open source tools.

Bundles aren't bad. Bundles that you don't create yourself are what's bad.
