### ISSUE TITLE
Need a Utxo input item for signing

### ISSUE THREAD

**Issue by amirh3n** [bitcoinjs/bitcoinjs-lib#1565]
I am trying to transfer 0.005 BTC from three addresses listed below using bitcoinjs-lib

ms5JLRCTKX6uofiYenTLidVXD7qjQBmdEV

mm7HDJ2M5HuJU4zii8LR5TXaCznCMn4vDf

mj5RmSNP97FfqV353szFBMvqTiH8bCqkBD

and this is what I have done:

```
exports.transferMoneyBatch = async (dstAddress, amount, path) => {
  try {
    const keys = require('../config/keys');
    let withdrawalAmount = sb.toSatoshi(amount);

    const phrase = keys.Mnemonic;
    const network = bitcoin.networks.testnet;

    const psbt = new bitcoin.Psbt({ network });
    const seed = await bip39.mnemonicToSeed(phrase);
    const root = bip32.fromSeed(seed, network);

    const childs = [];
    const addrs = path.map((record) => {
      const child = root.derivePath(record);
      const { address } = bitcoin.payments.p2pkh({
        pubkey: child.publicKey,
        network,
      });

      childs.push(child.toWIF());
      return address;
    });
    const _addrs = addrs.join(';');

    const addresses_live = await instance.get(
      '/addrs/' + _addrs + '?unspentOnly=true'
    );

    addresses_live.data.forEach((record) => {
      if (withdrawalAmount > 0)
        record.txrefs.forEach((txRecord) => {
          withdrawalAmount = withdrawalAmount - txRecord.value;
          psbt.addInput({
            hash: txRecord.tx_hash,
            index: txRecord.tx_output_n,
          });
        });
      else
        for (var i = addrs.length - 1; i >= 0; i--) {
          if (addrs[i] == record.address) {
            addrs.splice(i, 1);
            childs.splice(i, 1);
          }
        }
    });

    if (withdrawalAmount == 0)
      psbt.addOutputs([
        { address: dstAddress, value: sb.toSatoshi(amount) },
        {
          address: addrs[addrs.length - 1],
          value: Math.abs(withdrawalAmount),
        },
      ]);
    else psbt.addOutput({ address: dstAddress, value: sb.toSatoshi(amount) });

    childs.forEach((record, index) => {
      const w = bitcoin.ECPair.fromWIF(record, network);

      psbt.signInput(index, w);
    });

    psbt.finalizeAllInputs();
    const transaction = psbt.extractTransaction();
    const signedTransaction = transaction.toHex();
    console.log(signedTransaction);
  } catch (error) {
    console.log(error.message);
  }
};
```
I am getting Need a Utxo input item for signing error where I try to sign inputs.

**Comment by junderw** [comment]
for p2pkh you need to fetch the full raw transaction parent for each input.

Then put that Buffer in the addInput

**Comment by amirh3n** [comment]
@junderw can you provide me an example, please ??

**Comment by junderw** [comment]
integration tests, read them.

**Comment by ryuheimat** [comment]
> @junderw can you provide me an example, please ??

did you solve?

**Comment by bestbrain10** [comment]
@junderw 

I'm still having this issue, my inputs are matching the indicated format

```js
const keyPair = bitcoinLib.ECPair.fromWIF(from.privateKey, network);
const transaction = new bitcoinLib.Psbt({ network });

const inputs =  [{
      hash: '32db01d0aa429a6f429abaed816effd3cf2ed30034f304c5f250595df7203a18',
      index: 1
  }]
  
  const outputs = [
    { address: to.address, value: amount },
    { address: from.address, value: change }
  ];
```

but this:

```js
transaction.addInputs(inputs)
    .addOutputs(outputs)
  .signAllInputs(keyPair)
```

would give:
```js
Error: No inputs were signed
```

but then if I try to sign with a loop like this:

```js
inputs.forEach((ref, i) => {
    transaction.signInput(i, keyPair);
 });
```
then I get:

```js
Error: Need a Utxo input item for signing
```
I have been going through the integration test like you suggested but I haven't really found anything helpful.




> integration tests, read them.

**Comment by junderw** [comment]
You haven't read the psbt transaction integration tests.

Your inputs require either a nonWitnessUtxo or a witnessUtxo object depending on whether the script is segwit or not.

**Comment by Douglasacost** [comment]
In case someone need it, here is the correct model for inputs without Segregated Witness, where input.hex is the raw UTXO 
```
...
psbt.addInput({
  hash: input.hash,
  index: input.index,
  nonWitnessUtxo: Buffer.from(input.hex!, 'hex'),
})
...
```

**Comment by miketery** [comment]
Not sure where others are at but here's what my code looks like for p2wpkh inputs.

```
psbt.addInput({
    hash: input.txid,
    index: input.vout,
    witnessUtxo: {script: input.witnessScript, value: input.value }
})
```

where witnessScript is:
```
bitcoin.payments.p2wpkh({
    pubkey: pubKey, network: network
}).output
```

**Comment by junderw** [comment]
p2wpkh and p2sh-p2wpkh do not require a `witnessScript`

Speaking purely from a protocol perspective, the first item on the witness stack (where the witnessScript goes in p2wsh) is the compressed pubkey, not the p2wpkh output script.

**Comment by miketery** [comment]
@junderw - thanks for the help. I updated my comment above - I believe I misnamed the `output_script` as `witnessScript`.

**Comment by junderw** [comment]
Transaction size is not the same as PSBT size.

The nonWitnessUtxo data is not included in the Transaction size.

The easiest way to measure the tx size is to sign and create one transaction with a temporary fee/change amount, then get the vSize of the Transaction (through its method), and use that to calculate the required fee and re-do the transaction.

**Comment by bormisov1** [comment]
> Transaction size is not the same as PSBT size.
> 
> The nonWitnessUtxo data is not included in the Transaction size.
> 
> The easiest way to measure the tx size is to sign and create one transaction with a temporary fee/change amount, then get the vSize of the Transaction (through its method), and use that to calculate the required fee and re-do the transaction.

Thanks for your reply, it's much more clear now. Could you also suggest something for my case where I, as a backend, have to sign inputs on remote mobile device, and then `updateInput`s with the signature? I found where you said one has to imitate Signer to eavesdrop the hash for signature and I did this with proper public key. However, I'm stuck at step where I `updateInput` with `partialSig`.
My signature in hex is 140 chars long. Passing `Buffer.from(sig, 'hex')` inside partialSig throws `Data for input key partialSig is incorrect: Expected { pubkey: Buffer; signature: Buffer; } and got [{"pubkey":{"type":"Buffer","data":[2,233,254,17,162,241,134,55,184,170,108,235,133,160,47,239,218,24,1,202,181,156,101,18,162,253,124,185,30,142,62,127,171]},"signature":{"type":"Buffer","data":[48,68,2,32,9...`.
Found somewhere that somebody passed this instead: `bitcoin.script.signature.encode(Buffer.from(signatures[i], 'hex'), bitcoin.Transaction.SIGHASH_ALL)`, but this `encode` throws `Expected property "signature" of type Buffer(Length: 64), got Buffer(Length: 70)`.
So next naive thing I tried was cut off last 6 bytes to get 64: `bitcoin.script.signature.encode(Buffer.from(signatures[i], 'hex').subarray(0, 64), bitcoin.Transaction.SIGHASH_ALL)`. This thrown `Outputs are spending more than Inputs` with stack
```
expressjs_1  |     at inputFinalizeGetAmts (/usr/src/app/node_modules/bitcoinjs-lib/src/psbt.js:1252:11)
expressjs_1  |     at getTxCacheValue (/usr/src/app/node_modules/bitcoinjs-lib/src/psbt.js:856:3)
expressjs_1  |     at Psbt.getFeeRate (/usr/src/app/node_modules/bitcoinjs-lib/src/psbt.js:255:12)
expressjs_1  |     at checkFees (/usr/src/app/node_modules/bitcoinjs-lib/src/psbt.js:736:44)
expressjs_1  |     at Psbt.extractTransaction (/usr/src/app/node_modules/bitcoinjs-lib/src/psbt.js:247:7)
```
trying `disableFeeCheck: true` brings to the same throwing point but later:
```
expressjs_1  |     at inputFinalizeGetAmts (/usr/src/app/node_modules/bitcoinjs-lib/src/psbt.js:1252:11)
expressjs_1  |     at Psbt.extractTransaction (/usr/src/app/node_modules/bitcoinjs-lib/src/psbt.js:251:5)
```
I'm guessing `Outputs are spending more than Inputs` might be due to lack of correctly signed spending inputs? My input clearly has 9694, I'm trying to transfer 1000 to myself with second output of 3694 going to myself too. So 5000 reserved for fee.
Do you have any suggestions for my case?

**Comment by junderw** [comment]
Please post an example signature (140 hex) and I'll tell you what to do.

**Comment by bormisov1** [comment]
> Please post an example signature (140 hex) and I'll tell you what to do.

@junderw 3044022009ee1af78b16e6e922348ba16064805fb32f3f6056c6fc2060b64e648536cc4a02205d23dcca3bbe8f18c5e84e8ffe4ee592bb624f0b2c7e19b704eae41b0f1e62fd

**Comment by bormisov1** [comment]
I think I solved my problem, I simply didn't have enough left on the input. Seems like a bug to me that passing `true` as `disableFeeCheck` doesn't prevent `Outputs are spending more than Inputs` error, while leaving more of input for the fee does prevent it, what do you think?

**Comment by junderw** [comment]
The "fee check" is referring to the check against the maximumFeeRate (the default is 2500 sat/vByte, if you go over that it will throw an error on extraction.

If outputs are sending more than inputs, that is an invalid transaction and should not be created.

**Comment by junderw** [comment]
> tried supplying them concatenated, then tried to .reverse() concatenated Buffer, none worked

The Signer interface's `sign()` method expects a 64 byte signature. 32 byte r value (big endian) followed by a 32 byte s value (big endian)... in the DER format, r and s values can be 33 bytes or even 1 byte, since DER uses variable size encoding, so you must ensure that the r and s values are normalized to 32 bytes. `bitcoinjs.script.signature.decode` can be used, but you need to have the sighash byte at the end (your 70 byte signature does not include the sighash byte, so you can just add 0x01 and ignore the sighash output of the decode function)

**Comment by bormisov1** [comment]
> `bitcoinjs.script.signature.decode` can be used, but you need to have the sighash byte at the end (your 70 byte signature does not include the sighash byte, so you can just add 0x01 and ignore the sighash output of the decode function)
Wow, thank you very much for that, already had this `asn1.js` package parsing it, but it's sure more concise with `bitcoinjs.script.signature.decode` and no extra package required 😎
