### ISSUE TITLE
Output address

### ISSUE THREAD

**Issue by dimitriib** [bitcoinjs/bitcoinjs-lib#1587]
When I trying decode output address via this code 

bitcoin.address.fromOutputScript(output.script);

I receiving:
"04ea1feff861b51fe3f5f8a3b12d0f4712db80e919548a80839fc47c6a21e66d957e9c5d8cd108c7a2d2324bad71f9904ac0ae7336507d785b17a2c115e427a32f OP_CHECKSIG has no matching Address"

But I know that this address exists, I able to see it on any blockhain explorer websites.

It's transaction: a3b0e9e7cddbbe78270fa4182a7675ff00b92872d8df7d14265a2b1e379a9d33

**Comment by junderw** [comment]
P2PK does not have a standardized address format.

Block Explorers are converting P2PK output script to P2PKH output script, then creating the address.

This is bad, as that would mean that one address can have two possible scripts.

Block Explorers probably decided to do this because there is no address format for P2PK but they didn't want to show users a long pubkey, and they figured "if they own the pubkey they could also spend a P2PKH to that pubkey, so just use P2PKH address for P2PK".

That design decision for their block explorers is wrong, bad, dangerous, and not good.

Blockstream (a company filled with people who understand Bitcoin extensively) made a block explorer that gets it right.

Your transaction:

(blockchain)
Transaction:
https://www.blockchain.com/btc/tx/a3b0e9e7cddbbe78270fa4182a7675ff00b92872d8df7d14265a2b1e379a9d33
"Address" (not really):
https://www.blockchain.com/btc/address/1BBz9Z15YpELQ4QP5sEKb1SwxkcmPb5TMs

(blockstream)
https://blockstream.info/tx/a3b0e9e7cddbbe78270fa4182a7675ff00b92872d8df7d14265a2b1e379a9d33
"Address" (not really):
https://blockstream.info/address/1BBz9Z15YpELQ4QP5sEKb1SwxkcmPb5TMs

**Comment by junderw** [comment]
if you want to mimic this poor design decision, then you would need to convert the p2pk to p2pkh. get the output script, and create an address from that.

This can easily be done in one line using the Payments API.

**Comment by dimitriib** [comment]
@junderw can you show me how it need to do it?
I found only this solution:
It's not looks good as for me...
But I don't know another way

`let suppliedKey = '';
let originalError = '';
const amount = o.value;
try {
  address = bitcoin.address.fromOutputScript(o.script);
} catch (e) {
  originalError = e.message;
  suppliedKey = e.message.split(' ')[0];
}
if(!address && suppliedKey) {
  try {
    const uncompressedHex = bitcoin.ECPair.fromPublicKey(Buffer.from(suppliedKey, 'hex'), { compressed: false }).publicKey.toString('hex');
    address = bitcoin.payments.p2pkh({ pubkey: new Buffer(uncompressedHex, 'hex') }).address;
  } catch (e) {
    // console.log('e', e);
    // console.log('originalError', originalError);
  }
}`

**Comment by junderw** [comment]
No, this is dangerous, so I will not recommend you a secure way to do a dangerous thing.

My recommendation is to not show an address, or show bitcoin.script.toASM(output.script) or something instead of an address.
