### ISSUE TITLE
cant get output address OP_CHECKMULTISIG has no matching Address

### ISSUE THREAD

**Issue by dimitriib** [bitcoinjs/bitcoinjs-lib#1592]
When I trying to get address from output script via bitcoin.address.fromOutputScript(tx.outs[0].script)
then I reiciving:
"OP_1 0351efb6e91a31221652105d032a2508275f374cea63939ad72f1b1e02f477da78 00f2b7816db49d55d24df7bdffdbc1e203b424e8cd39f5651ab938e5e4a193569e OP_2 OP_CHECKMULTISIG has no matching Address"

really no way to get the address?

**Comment by junderw** [comment]
There is no multisig address.

**Comment by junderw** [comment]
P2SH addresses, yes.
P2WSH addresses, yes.

"Multisig" addresses do not exist.

**Comment by junderw** [comment]
I think blockchain info used to parse all the pubkeys and convert all the pubkeys into P2PKH addresses and display multiple P2PKH addresses...

This caused a lot of people problems, because multisig wallets are not designed to spend money sent to their single key. But the block explorer showed single-sig address of a key used for Multisig.

**Comment by junderw** [comment]
So many people would see the 3 single sig addresses, send to one of them (thinking they are sending to multisig) and lose money.

In fact, that problem was one of the reasons why P2SH was created.

But for raw multisig (without P2SH) there is no address format. I would just replace it with some string like "Multisig(2 of PUBKEYHEX1 PUBKEYHEX2 PUBKEYHEX3)" or something

**Comment by dimitriib** [comment]
Many thanks, Jonathan!
