### ISSUE TITLE
I have tried to adapt alice-bob csv test to p2sh-p2wsh but it doesn't work

### ISSUE THREAD

**Issue by educob** [bitcoinjs/bitcoinjs-lib#1605]
This is the code. It doesn't work. Please help.

I have also tried substituting p2sh with p2wsh but I get error: `Error: non-mandatory-script-verify-flag (Witness program was passed an empty witness) (code 64)`
 
I need a solution to either of those problems (the above error or the code below).

Thanks.

```
async function test3() {
    const sequence = bip68.encode({ blocks: 5 })

    const output = csvCheckSigOutput(alice, bob, sequence)
    let p2wsh = bitcoin.payments.p2wsh({ redeem: { output, network: regtest }, network: regtest })
    let p2sh = bitcoin.payments.p2sh({ redeem: p2wsh, network: regtest })
    const address = p2sh.address

    // fund the P2SH(CSV) address
    const unspent = await regtestUtils.faucet(p2sh.address, 2e4)

    const tx = new bitcoin.Transaction()
    tx.version = 2
    tx.addInput(idToHash(unspent.txId), unspent.vout, sequence)
    tx.addOutput(toOutputScript(regtestUtils.RANDOM_ADDRESS), 1e4)

    // {Alice's signature} OP_TRUE
    const signatureHash = tx.hashForSignature(
      0, // utxo 0
      output,
      hashType,
    )

    const input = bitcoin.script.compile([ // path
      bitcoin.script.signature.encode(alice.sign(signatureHash), hashType,),
      bitcoin.script.signature.encode(bob.sign(signatureHash), hashType),
      bitcoin.opcodes.OP_FALSE, //in test is OP_TRUE but I think it  has to be OP_FALSE
    ])

    const redeemScriptSig = bitcoin.payments.p2sh({
      network: regtest,
      redeem: {
        output,
        input
      }
    }).input     
                     // utox indes
    tx.setInputScript(0, redeemScriptSig)


// into the future
    await regtestUtils.mine(10)

    await regtestUtils.broadcast(tx.toHex())

    await regtestUtils.verify({
      txId: tx.getId(),
      address: regtestUtils.RANDOM_ADDRESS,
      vout: 0,
      value: 7e4,
    })
    
}
```

**Comment by junderw** [comment]
you need to use the segwit sighash, and when constructing the input and witness stack you need to use both p2wsh AND p2sh together.

**Comment by educob** [comment]
Hi Jonathan.

Could you please write the code for that? I really don't know how to do it.
I have tried all combinations possible.

Thanks.

**Comment by educob** [comment]
Could you please adapt the 2nd fuction ('can create (but fail to broadcast via 3PBP) a Transaction where Alice ' +
      'attempts to redeem before the expiry (simple CHECKSEQUENCEVERIFY)',)  for segwit?

**Comment by junderw** [comment]
> csvGetFinalScripts

csvGetFinalScripts is only put in there as a placeholder, it makes zero security checks and can be insecure. It only exists to show you an example of "What kind of function should I pass to finalizeInput to finalize for arbitrary scripts?"

Do not use it in production.

> Could you please write the code for that? I really don't know how to do it.

Here's what will happen:

1. I write the code for you.
2. You don't understand how it works.
3. You change something, it doesn't break your tests, so you deploy it.
4. Turns out your users' funds are lost or sent to a blackhole or locked for 5000 years when they only wanted it locked for 3 weeks.

I even wrote down in the test file:

>   // Note: bitcoinjs-lib will not offer specific support for problems with
>  //       advanced script usages such as below. Use at your own risk.

So even the extent that I have helped you thus far is much more than I have promised.

But I will leave this issue open in case someone else wants to discuss with you a secure way to do what you want to do.

> but I need the one with Transaciton.

Out of curiosity, why do you **need** to use a specific class?

**Comment by educob** [comment]
Hi Jonathan.

Thanks for answering.

I understand your points. I have a hard time trying to understand what I am doing. It must sound crazy for most people.
My goal is to help achieve bitcoin mass adoption. For that I am developing a very ambitous web service (100% non-custodial impossible to make people understand that's even possible) that offer an amazing functionality.
I have developed a bitcoin script (not really one but a variable one based on the number of heirs) to solves the inheritance problem of not passing accss to private keys until the death (both using a third party and without third party), I have found the way to offer non-custodial multi-user lightning network services, etc.
I am alone developing this for over 2 years full time (seven days per week the whole day).

You don't know how many times I have thought about offering you part of the company so you offer the security/quality for the scripts. Now I am almost ready to go online as everything works, we have a new UI, etc.

Would it be any change to discuss this topic at length?

Regarding the specific class usages, I already have developed the script with transaction builder and the code for the second test is almost the same to what I have so it would be very convenient.
But as it doesn't work I am right now modifying the psbt test tyring to adapt it for distruibuted singature, etc.

Thanks.

**Comment by educob** [comment]
I made it work with psbt.

The most difficult part was making generic the callback funciton passed to `psbt.finalizeInput`

Thanks.

**Comment by junderw** [comment]
Glad to hear!

> The most difficult part was making generic the callback funciton passed to `psbt.finalizeInput`

Yes. This callback is what makes sure that you have the correct info for the script and then builds the scripts, and throws an error if there is not enough info to build the scripts.

It is a very important callback. But instead of having to modify Psbt to use a custom script, the callback method is better I think.
