### ISSUE TITLE
BIP-143 prevtx UTXO vulnerability

### ISSUE THREAD

**Issue by sidhujag** [bitcoinjs/bitcoinjs-lib#1625]
I think achow updated BIP-143 to reflect a PSBT vulnerability back in June:

https://github.com/spesmilo/electrum/pull/6198

Just making sure this library isn't affected? AFAIK witness utxo's only need txid/outindex while non-witness require full prevtx, should witness also require prevtx?

Thanks,
Jag

**Comment by junderw** [comment]
PSBT is still vulnerable as a protocol, since it doesn't *require* full prevtx for everything.

This was done to allow for backwards compatibility.

The best we can do is use console.warn.

That said, this vulnerability is not a library-level vulnerability. All mitigations must be done at the wallet application level, and we currently allow for all the tools apps need to mitigate it.
