### ISSUE TITLE
Need raw transaction to spend P2PKH utxo? Design flaw?

### ISSUE THREAD

**Issue by pedr0-fr** [bitcoinjs/bitcoinjs-lib#1633]
I am building a transaction and I want to fund it with P2PKH and P2SH(P2WPKH) utxos. From what I have seen, the way to do it is:

```javascript
// ...
psbt.addInput({
hash: TXID,
index: TX_OUT,
nonWitnessUtxo: Buffer.from(TX_HEX, 'hex')
}) 
```
Given that it's enough to provide the `scriptPubKey` of these utxos for signing, why do you ask for the whole raw transaction `nonWitnessUtxo`? Is there a workaround?

**Comment by junderw** [comment]
PSBT is defined in a BIP. (BIP174)

The BIP requires that non-segwit inputs have the full transaction in order to verify the value of the input.

(Since segwit actually signs the input value itself, this is not needed, but non-segwit only signs the previous TX_HASH("ID")... so we must verify the input value by checking the previous TX's output that you are spending (since the output contains the value) and THEN verify that the full transaction CONTAINING that output's hash is equal to the TX hash in the input we are signing (the only way to verify the hash is equal is to have the entire transaction so we can hash it.)

There is a way to workaround this check, but since this check is required by the BIP, using this workaround will disable `toHex` `toBase64` etc. (Since if you pass a PSBT without the full tx to another application and it sees "non-segwit" + "no full tx" it will break and throw errors)

However, you will need to read the `ts_src/psbt.ts` source code and look at the main Psbt class and figure out how to workaround it yourself.

I will not offer any support on how to use Psbt insecurely, you will need to figure it out on your own. (There is a way, though)

**Comment by pedr0-fr** [comment]
I didn't know that non-segwit inputs didn't sign the amount. I guess the goal is to prevent wallets from accidentally signing transactions with overly high transaction fees... Still not 100% convinced this check should necessarily be done inside the PSBT, but that's an issue with BIP 174... Thanks!

**Comment by junderw** [comment]
Well, if you're just signing in one go and have no need to export the PSBT and send to another wallet, you can just flip the switch in the cache from false to true and you can sign non-segwit with only a `witnessUtxo`.

As far as the BIP is concerned, BIPs are not perfect. If you have suggestions, definitely bring it up on the BIP repo or the mailing list.

**Comment by educob** [comment]
Hi Jonathan.

Could you please explain in more detail "you can just flip the switch in the cache from false to true and you can sign non-segwit with only a witnessUtxo"?

Thanks.

**Comment by junderw** [comment]
Hi @educob 

> However, you will need to read the ts_src/psbt.ts source code and look at the main Psbt class and figure out how to workaround it yourself.
> 
> I will not offer any support on how to use Psbt insecurely, you will need to figure it out on your own. (There is a way, though)

I don't want to encourage this usage, so I will not go into further detail.

If you read the source code, it will be painfully obvious what to do.

Thanks.

**Comment by educob** [comment]
Hi again.
Thanks for answering.

Can it be done easily with the old version of the library that used transactionBuilder?
Thanks.
