### ISSUE TITLE
how does bitcoinjs-lib grab utxo

### ISSUE THREAD

**Issue by novaknole** [bitcoinjs/bitcoinjs-lib#1646]
So, Let's say I want to create a transaction by using bitcoinjs-lib.

As far as I can see, this library doesn't provide the help so that it can automatically figure out/grab unpent transactions for inputs and create a transaction magically.

My question is: Am I the one who has to know unspent transactions that I want to use for the inputs in advance ?

If the answer is no, then can you point me to the bitcoinjs-lib file that does this ?

If the answer is yes, how do I get unspent transactions ? By looking at my transaction list on blockchain and getting each one of them's txid and vouts seem not reasonable. Any idea ?

**Comment by junderw** [comment]
Yes. You need to know your own transactions.

There are many ways of doing this:

1. Generate as many addresses as you need (and you can add new addresses accordingly) and add them to your Bitcoin Core wallet using `importmulti` `importaddress` etc. (If you plan on using multiple calls to add a large amount of addresses, make sure the `rescan` option is set to false for every call except the last one. One call with `rescan` set to `true` (the default) it will start scanning the blockchain from block 0 and take a very long time, so make sure you add all the addresses you need (and maybe excess) before making a call with rescan. If you know that the address has not been used, you don't need to rescan, and it will just start watching for UTXOs after the import without checking past blocks. Then you just need to use `listunspent` to get the UTXOs.
2. Use a 3rd party API like https://github.com/Blockstream/esplora/blob/master/API.md which can be hosted by someone else (like https://blockstream.info/ ) or you can use the open source repository to run your own esplora on top of your own Bitcoin Core, making it easier to query (since esplora indexes all UTXOS by address etc.)

If you want to use your own node, 1 is more efficient compared to 2... if you want to use someone else's node (ie. blockstream's node) 2 is easier.
