### ISSUE TITLE
Integration tests failing: 502 Bad Gateway

### ISSUE THREAD

**Issue by 7-of-9** [bitcoinjs/bitcoinjs-lib#1659]
Hi all, I guess maintainers are probably aware, but `npm run intregration` results in numerous 502's, presumably from a 3PBP being down.

Any workaround suggested, or something I'm doing wrong? I'm keen to see testnet TX's going E2E.

**Comment by junderw** [comment]
Thanks for letting us know. There's no guarantee for uptime with that. It's only meant as a courtesy for people who don't want to run a docker container / forget to run their local docker container, we have a server running the container that crashes from time-to-time (since people do weird things to it and break it)

For now, please do the following: (It's also much faster)

```bash
# This will pull the docker image we are running on the server (it's not testnet, it's regtest)
$ docker run -d -p 8080:8080 junderw/bitcoinjs-regtest-server
# adding the env var to point to the locally running docker container
$ APIURL=http://localhost:8080/1 npm run integration
```

**Comment by junderw** [comment]
I rebooted the server. It seems to be working now.
