### ISSUE TITLE
How to use this library correctly？

### ISSUE THREAD

**Issue by lyon0712** [bitcoinjs/bitcoinjs-lib#1682]
## How to use this library correctly？
I am a back-end developer, and I have been in contact with Ethereum-related business development. Because of customer needs, I need to quickly get started with Bitcoin development, but I don’t know anything about it.

I have developed applications that interact with Ethereum by using third-party libraries that encapsulate RPC interaction, such as Ethers.js. So I thought bitcoinjs-lib has the same way of interacting as Ethers.js, but after almost two days of study, I found that it doesn't seem to be the case. Is that right?

I hope you can help me and tell me the correct usage of bitcoinjs-lib, or my idea is wrong.

Thank you very much !!!
### Current situation
1. I have run bitcoind service on my server.
2. I am developing an application based on node.js

### Demand
1. Get the balance of the specified wallet address through my node
2. Get transaction details of input txhash (txid) through my node
3. Broadcast the signed and valid transaction data through my node
4. How to automatically monitor that there is a new block on the blockchain

**Comment by junderw** [comment]
This is a client library. It takes input data and provides output.

It doesn't connect to a node directly since bitcoin is stateless.

There are many ways to get data from bitcoind.

1. Use the wallet RPC methods to register addresses or output descriptors ahead of time. Then use the wallet RPC methods (via  bitcoin-rpc library etc.) to get the data to use with this library.
2. Use an open source block explorer app sitting on top of your node. More overhead, but the API interface is easier, and you can look up any txid or any address at any time. (most other solutions will only watch for tx related to a specific wallet you've registered ahead of time with bitcoind)

1-3 of your demands are answered by the above.

As for 4, bitcoind actually has a zeromq message queue you can use to get messages on every new block. I also think SOME open source block explorer apps offer some sort of websocket for block messages.

For 1: 
https://www.npmjs.com/package/bitcoind-rpc

For 2 there are a couple of options:
https://github.com/Blockstream/esplora
https://github.com/romanz/electrs
https://github.com/janoside/btc-rpc-explorer

As far as what data you need and how you will use it to create and sign transactions, the integration tests are great examples.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/239711bf4ef00651af92049bcdf88b12252b945c/test/integration/transactions.spec.ts#L12-L73

**Comment by junderw** [comment]
Just FYI this example is using `ECPair` single keys for simplicity sake.
bip32 HD keys are the norm.

**Comment by lyon0712** [comment]
@junderw 

Thank you for your help!
But it doesn't seem to solve my problem, the following is the result of my test.

For demand 1:
https://www.npmjs.com/package/bitcoind-rpc 
I used the method provided by this library, but getbalance can only get the balance of my node wallet, not the balance of any wallet address.

![image](https://user-images.githubusercontent.com/77255416/109274073-f62bbe00-780a-11eb-8d81-c835e07d2c4c.png)

If I change the first parameter to "×", there will be no problem
![image](https://user-images.githubusercontent.com/77255416/109274026-e4e2b180-780a-11eb-9c84-c26f0a62362d.png)

**Comment by junderw** [comment]
> but getbalance can only get the balance of my node wallet

That's how a node works. You register your addresses ahead of time, and it will rescan (you can register 10000000 addresses with rescan: false, then on the last address register with rescan: true and it will scan the blockchain for all 10000000 addresses.)

If you want any address, use something like esplora, it indexes all the addresses on the blockchain, which makes youre node 3-4x larger storage requirements. But you can do a simple query for balance of any address.

**Comment by lyon0712** [comment]
@junderw 
Thank you very much for your help
