### ISSUE TITLE
Is there a use case for adding two private keys?

### ISSUE THREAD

**Issue by melvincarvalho** [bitcoinjs/bitcoinjs-lib#1689]
Maybe a simple use case but I was looking for a way to add two private keys and have them reflected in the public keys

Useful for vanity wallets and other things

Not sure if this is the right repo, but just writing this here, as it said to ask for use cases

**Comment by junderw** [comment]
BIP38 has a multiply mode where you can outsource the mining of a vanity address.

[Here's the BIP](https://github.com/bitcoin/bips/blob/1f0b563738199ca60d32b4ba779797fc97d040fe/bip-0038.mediawiki#Encryption_when_EC_multiply_mode_is_used)

This is more efficient than addition because in order to perform addition, the miner would need to perform one multiplication (from the generator point) to find "their" pubkey, then add that pubkey to "your" pubkey.

Whereas, using multiplication, all they need to do is pretend "your" pubkey is the generator point.

```
- given P1, asked to find a p2 which when combined will create a vanity address from P3
- lowercase p{x} is private key, upper case P{x} is public key, and G is the generator point

addition loop:
P2 = p2 * G
P3 = P1 + P2
*check if P3 matches vanity*

multiplication loop (one less operation):
P3 = p2 * P1
*check if P3 matches vanity*

private key recovery for
addition:
p3 = p1 + p2
multiplication:
p3 = p1 * p2
```

So as far as vanity addresses are concerned, no there's really no use case for addition.
