### ISSUE TITLE
Help Me Understand PSBT with redeemScript and publicKeyHex

### ISSUE THREAD

**Issue by mdbiscan** [bitcoinjs/bitcoinjs-lib#1713]
My wallet received bitcoin. I was able to download the transaction data off the blockchain and I'm using that data to QA against. But, I am unable to validate the input with my wallet.

This is the script that builds a transaction:

```javascript
const Psbt = new Bitcoin.Psbt();

Psbt.addOutput({ address, value });

const signature = Bitcoin.ECPair.fromWIF(wif);
const payment = Bitcoin.payments.p2sh({
  redeem: Bitcoin.payments.p2wpkh({ pubkey: signature.publicKey }),
});

inputs.forEach((input) => {
  Psbt.addInput({
    hash: input.txID,
    index: input.idx,
    redeemScript: payment.redeem.output,
    witnessUtxo: {
      script: Buffer.from(input.publicKeyHex, 'hex'),
      value: input.value,
    }
  });
    
  Psbt.signInput(input.idx, signature);
});

Psbt.validateSignaturesOfAllInputs();
Psbt.finalizeAllInputs();

return Psbt.extractTransaction();
```

on `Psbt.signInput`, I get the following error:

```shell
Error: Can not sign for this input with the key [actual key edited out here]
```

My head is spinning and I can't tell what I'm doing wrong. I've tried with outputs from more than one transaction and get the same error on the same key each time.

**Comment by junderw** [comment]
First of all, you need to add all inputs before you sign any inputs, so if `inputs.length > 1` your code will fail, since adding the second input will invalidate the signature you made on the first input.

Second of all. You might want to add an assert in the loop that checks if
`payment.output.toString('hex') === input.publicKeyHex`

If that assert fails, then you know that you are using the wrong wif key for your signing OR the input.publicKeyHex is wrong.

---

My 6th sense tells me that `input.publicKeyHex` is just the public key... which you don't want.

Try using `payment.output` as your script in the witnessUtxo. That should work. It will also help you find what data you need from your explorer.

Also, remember to make 2 loops, one for adding inputs and one for signing all of them after adding everything.

**Comment by junderw** [comment]
Other than those 2 points, this code looks ok to me.

**Comment by mdbiscan** [comment]
Thanks, that was actually a typo. I am using `payment.redeem.output`.

I'll try your advice on `inputs.length`

**Comment by mdbiscan** [comment]
I guess I don't understand how this works when we use the same type of output for `utxo.script` and `redeemScript`. If they are the same thing, why do we bother with adding them both?

**Comment by junderw** [comment]
One more problem I missed:

`signInput` index is "The x-th input of this transaction" x value
`addInput` index is "The x-th output of the transaction that is pointed to with `hash` which is the output you wish to spend"

So if you want to sign all, and let's say you have 5 inputs, you should loop from 0-4 and use those to sign.

idx value for addInput could be or something really high since it's referring to the index of the outputs of the previous transaction.

Also, we have a convenience function called signAllInputs which will sign all the inputs it can find that match your key. (Be warned, if any of your inputs don't match the key, it will silently ignore them, it will only throw an error if no input matches your key.)

```js
for (let i = 0; i < Psbt.inputCount; i++) {
  Psbt.signInput(i, signature);
}

// OR

Psbt.signAllInputs(signature);
// and get an error during extractTransaction if any of the inputs don't match your key.
```

**Comment by mdbiscan** [comment]
Thanks. I will always use extract transaction, so it should theoretically see the error. The method is called in a try/catch.
