### ISSUE TITLE
reading the wallet  balance 

### ISSUE THREAD

**Issue by moblizeitllc** [bitcoinjs/bitcoinjs-lib#1753]
I have created a wallet address using below code:

`
 const keyPair = ECPair.ECPair.makeRandom();
 const { address } = bitcoin.payments.p2pkh({ pubkey: keyPair.publicKey, network: diviMainnet });
`
i am storing the info as below in my DB.

`
   {
     "pubKey": address,
     "wif": keyPair.toWIF()
   }
`

Now at a later point i want to read the balance the above address holds. so did so far like below

`
     const alice = ECPair.fromWIF(
            wallet.wif(),
      );
`

At this point, i am stuck to find an example as how do i now use above part to read the wallet balance.

**Comment by junderw** [comment]
You have a few options:

1. Run your own bitcoin node
  a. You can connect to your node via RPC to get info about your wallet, but this requires that you add the address(es) to your node's wallet (you can do so as "watch-only" as well, without uploading the private key to the node, only the address)
  b. You can run software on top on your node that indexes all addresses for you (so you can ask that software "what is the balance / utxos of this address?" for any address that exists.
2. Use an external API (You are trusting these site maintainer to not lie to you, be careful)
  a. One example: [Blockstream . info](https://github.com/Blockstream/esplora/blob/a43f38753b2dd215f0cc07b33783c47b2915d2f5/API.md#esplora-http-api)
  b. Another: [mempool . space](https://mempool.space/api)

**Comment by moblizeitllc** [comment]
so little lost here. why do i need to run my own bitcoin node. if i created the wallet myself and own the ECPair with all info then cant i use that info anytime to check the funds on that address?  i did not require a node to generate the wallet so why to check the balance?

**Comment by junderw** [comment]
1. You ask me to pay you 1 BTC
2. I secretly own blockcypher, and I change my API to lie to you about the balance of your address
3. You are tricked into thinking I paid 1 BTC when I did not
4. You send me the product
5. I win, you lose :-P

Also there are less obvious ways to lie and steal:
1. Your address has 1 utxo of value 10 BTC
2. I am a miner who secretly owns blockstream API
3. I lie to you and say your utxo is worth 9 BTC
4. You create a transaction, and since you use `input value total - output value total` to calculate fees, I lied to you about input value, so you think you are giving the miner XBTC fee but you are actually giving me XBTC + 1BTC fee. So I stole your 1BTC.

These are not obvious when you don't understand how bitcoin works...

So like I said in the other issue, pleeeeeeeease learn more about Bitcoin in general before creating a wallet application.

There are soooo many ways to shoot yourself in the foot.

**Comment by junderw** [comment]
I highly recommend installing https://btcpayserver.org/ BTCPay server on a server you own.

BTCPay makes it super easy to manage wallets, and you get a pretty looking ecommerce store that accepts bitcoin payments through both normal addresses and lightning invoices.

It's open source, I am close friends with the guy who started it, and I have worked on it a little bit. (I maintain the NodeJS client library for dealing with NBXplorer and BTCPay (NBXplorer is the wallet component)

**Comment by Ray1010101** [comment]
Hello Broski can you give me kinda tutorial of the btcpayserver and will I be generating my own Bitcoin?

**Comment by junderw** [comment]
> tutorial
https://docs.btcpayserver.org/

> generate bitcoin?
No. BTCPay does not do mining. It only verifies transactions and offers you a nice wallet, API, and storefront fo e-commerce websites

**Comment by Ray1010101** [comment]
Ummm Good day mister I will like to discuss a short brief stuff with you if
you got a way to help me out I got funds on my Bitcoin wallet dashboard but
the funds is not on the wallet do you have an idea on how I can pull the
funds out????

**Comment by junderw** [comment]
Please ask BTCPay team on their mattermost chat server.

**Comment by Ray1010101** [comment]
Thanks for your response so can you pls tell me on how I will be able to
send the funds from just the dashboard to another wallet?
