### ISSUE TITLE
add payment classify

### ISSUE THREAD

**Issue by motorina0** [bitcoinjs/bitcoinjs-lib#1768]
In older versions of this lib the `classifyScript()` was exposed, but it has been retired afterwards.
Maybe because the old logic was using the `templates` approach which has also been removed.

However, the functionality itself is very useful:
 - a user provides a (`in/out`) script and the API returns the type of the script (`p2pkh`, `p2wsh`, etc)

This can be used on the UI (showing a label next to a tx input/output for example) but also in the business logic for taking certain decisions based on the payment type.

My question is if it is OK to expose a `classifyPayment()` method for the `payments` API.
This API allows as input only the fields that would help identify the payment type.

```
export interface PaymentClassify {
  output?: Buffer;
  data?: Buffer[];
  input?: Buffer;
  address?: string;
  witness?: Buffer[];
}

classifyPayment(PaymentClassify p): string
```

The logic is almost entirly already implemented in `Psbt` with `isPaymentFactory()`, it just needs to be extracted and exposed.

There might exist good reasons for **not** making this public, but I can't think of any right now.

**Comment by junderw** [comment]
This is a very difficult distinction to make, but bear with me.

So, with the classify utils in <=v5 and the PSBT isPaymentFactory stuff as well, we did not expose those APIs publicly.

When an API called classify that returns a string saying "p2wsh-p2wpkh" you are making a contract with the implementer that there is a certain level of correctness for any and all uses which that information could be used for.

Here's an example of one that I've heard of before:

1. Someone was using classify from v4 (even though it was "private")
2. They classified an input as p2pkh.
3. They didn't bother looking at the output of the tx pointed to by the parent tx.
4. They logged that spend as being "from" the p2pkh address, as they were indexing deposits and withdrawals using addresses / script hashes as an index.
5. The output was actually non-standard, so the balance was thrown off.

So for instances like this (witness/input) we can only use best guess logic. This is possible in PSBT because we have previous output data (via [non]WitnessUtxo) which we can check against.

There is also some danger associated with telling someone that the binary format of a given output fitting the P2PKH format as "this is definitely a payment to a pubkey hash" (implied by a "classify" API)

Case and point: [1BitcoinEaterAddressDontSendf59kuE](https://mempool.space/address/1BitcoinEaterAddressDontSendf59kuE)

There are other places in the existing API which do make some assumptions like this (*stares at address API*) but there has to be a line in the sand somewhere between usability of the API and not promising too much...

I don't feel comfortable with making such promises with a classify API.
