### ISSUE TITLE
Hybrid app with vue3, access to fetch at 'file:///...module.wasm' from origin 'null' has been blocked by CORS 

### ISSUE THREAD

**Issue by masanaka** [bitcoinjs/bitcoinjs-lib#1792]
The error happened when render the view witch will initial bip32 by tiny-secp256k1.
The code is based on sample 'https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/bip32.spec.ts'.  It is no problem when running as a web app, but failed as a hybrid app.
It's a cors issue, and it looks like it has something to do with the current  tiny-secp256k1 version use Rust crate compiled to WebAssembly.
I have no any idea with it, can somebody help me ?

**Comment by junderw** [comment]
WASM can only be served from a server. Browsers do not allow loading WASM modules from `file://` filesystem.

**Comment by junderw** [comment]
We have a React+webpack app which uses asyncWebAssembly experiment enabled and it works.

https://github.com/bitcoinjs/tiny-secp256k1/blob/v2.2.1/examples/react-app/webpack.config.js

Maybe something similar can be done with Vue.

You also may get better results asking on a Vue related forum, since this issue is with the bundler and not with this library.

The only thing we could possibly do is "Don't use WASM"... which is not something we are willing to do.

**Comment by junderw** [comment]
Alternatively, you can use v1 of tiny-secp256k1 with the latest bip32.

**Comment by masanaka** [comment]
@junderw 
Thanks a lot. 
I tried with tiny-secp256k1 v1.1.6, it works fine.
And about WASM with v2 on a hybrid app, I will continue to research it when I have enough time.
Thank you again!
