### ISSUE TITLE
Segwit bc1 address from private key

### ISSUE THREAD

**Issue by random9brat** [bitcoinjs/bitcoinjs-lib#1795]
Still searching for the answer... right now im stuck with this code and I could really need some help... playing around and trying to learn more about btc dev.

```
let bitcoin = require('bitcoinjs-lib');
const ECPair = require('bitcoinjs-lib/src/ecpair');

const keyPair = ECPair.fromWIF('KxCb6hLLBUwxJdThXnSb37gJPKmN5BiibRiA7MXQouAWtRyRTQmo');
const { address } = bitcoin.payments.p2wpkh({ pubkey: keyPair.publicKey });
console.log(address);
```

Im really new into this world of JS so be gentle, i guess i stuck with some imports etc but I really dont know what to do. I can feel that solution is one or two lines away but i really dont know what to do... 

Am i wrong or it bc1 segwit can be generated just with private key??

**Comment by junderw** [comment]
I understand you're new, but here's a tip for anything in life you're new to. "Read the manual."

Don't know how to put together an IKEA chair? Don't just randomly start nailing wood together. Read the manual.

Don't know how to use a library? Read the manual (README).

Let's read the README together:

1. OK, how do I install this library? hmm, I could just trial and error based on what I think it should be... OR I could read the README. Ok, what does the README say...

> ![Screenshot_20220416_081020](https://user-images.githubusercontent.com/11246316/163651487-d054dbe2-cc78-46a6-aa38-83e5d36afb3d.png)

2. Oh wow, so I need to provide my own key derivation by installing `ecpair` or `bip32` separately. That would be confusing if the only knowledge I had was based on copy pasted examples from older versions... OK... what does the bip32 README say?

> ![Screenshot_20220416_081219](https://user-images.githubusercontent.com/11246316/163651587-9ac0c252-0786-4ec3-9bf8-11710d4f1e18.png)

3. Oh... hmm, so I need to wrap `tiny-secp256k1` in order to use bip32. Looking at the ecpair README also shows something similar...

```js
const ecc = require('tiny-secp256k1');
const { ECPairFactory } = require('ecpair');
const ECPair = ECPairFactory(ecc);
```

**Comment by random9brat** [comment]
Hmmm...im still not doing something good, hope we can still communicate even if its closed:

```
const bitcoin = require('bitcoinjs-lib');
const ecc = require('tiny-secp256k1');
const { ECPairFactory } = require('ecpair');
const ECPair = ECPairFactory(ecc);

const keyPair = bitcoin.ECPair.fromWIF('KxCb6hLLBUwxJdThXnSb37gJPKmN5BiibRiA7MXQouAWtRyRTQmo');
var addr = keyPair.getAddress();

console.log(addr);
```

with this code im getting 13LzzJWrgRUM8Xtx9SnJa2Yn5aGruMQfEG not bc1.....

also when i try to run this im getting TypeError: Cannot read property 'p2wpkh' of undefined

```
const bitcoin = require('bitcoinjs-lib');
const ecc = require('tiny-secp256k1');
const { ECPairFactory } = require('ecpair');
const ECPair = ECPairFactory(ecc);

const keyPair = bitcoin.ECPair.fromWIF('KxCb6hLLBUwxJdThXnSb37gJPKmN5BiibRiA7MXQouAWtRyRTQmo');
const { address } = bitcoin.payments.p2wpkh({ pubkey: keyPair.publicKey });

console.log(address);
```

I have a feeling that we are close :))) thanks for helping me tho, i really appreciate it

**Comment by random9brat** [comment]
Holly molly what a ride this was...after 15+ hours i finally did it... i was using bitcoinjs-lib@3.3.2 not @6.0.1...

i changed it and we are good to go :D.... posting this here so if anyone ever have the same problem...

thanks again for the help junderw, you are the man.
