### ISSUE TITLE
Valid transaction data can't parsed by payments.p2sh

### ISSUE THREAD

**Issue by mahnunchik** [bitcoinjs/bitcoinjs-lib#1801]
Valid transaction data can't parsed by `payments.p2sh` method.

Tx: [dc1c1e4bae190370485d86123c0ddac20c27f86bf788be8370129589d07e83c0](https://blockstream.info/tx/dc1c1e4bae190370485d86123c0ddac20c27f86bf788be8370129589d07e83c0?input:0&expand)

```js
const payment = bitcoin.payments.p2sh({
  output: Buffer.from('a914b472a266d0bd89c13706a4132ccfb16f7c3b9fcb87', 'hex'),
  input: Buffer.from('5100', 'hex'),
});
```

Throws error: `TypeError: Input is invalid`

**Comment by junderw** [comment]
This is incorrectly categorized as p2sh by block explorers due to being an irregular script.

In actuality, when Bitcoin Core parses this script, it does not recognize it as p2sh, and instead it just runs it as a normal script, and the result is `1 1` on the stack.

If the "redeemScript" portion were actually being run, it would leave OP_FALSE (an empty buffer) on the top of the stack causing verification failure... so we know for sure that Bitcoin Core is not parsing this as a p2sh script.

You will notice that the scripthash in the output corresponds with the hash of an empty redeemscript (since OP_0 is equivalent to an empty buffer when hashing)

```bash
> bitcoin.crypto.hash160(Buffer.from([])).toString('hex')
'b472a266d0bd89c13706a4132ccfb16f7c3b9fcb'
```

So.

There are two ways one could parse this issue:

1. This is not a valid p2sh, so p2sh throwing should not be an issue.
2. The reason why p2sh is throwing is not helpful in this extreme edge case, so perhaps including a more descriptive error might be helpful.

I am leaning towards 1.

I will leave this issue open while I think about it.

Thanks for bringing up an interesting edge case!

**Comment by junderw** [comment]
After looking at the source of Bitcoin Core, it is definitely parsing it as a P2SH.

But when it goes to evaluate the redeemscript, it literally just skips the whole Eval loop because pbegin == pend from the beginning.

Then the OP_TRUE that was before the redeemscript (of OP_FALSE / empty buffer) is checked during the non-false stack check...

Weird...

I wonder if something similar can be done with P2WSH...

I am going to look into this a bit more when I have time.

**Comment by junderw** [comment]
Note that even if the PR is merged, this will still fail for a new reason: "redeem.output is too short"

Keep in mind that the p2sh `validate: true` checks are there to make sure people don't shoot themselves in the foot.

Payments should not be used for some sort of block parser, etc.

**Comment by junderw** [comment]
I verified that the same empty script is possible with P2WSH and P2SH-P2WSH, but neither of those two addresses have any history.

**Comment by mahnunchik** [comment]
Maybe there is sense to show warning `redeem.output is too short` and not to throw the error in such case?

**Comment by junderw** [comment]
That's the reason why `validate` exists.

What exactly is your use case?

**Comment by mahnunchik** [comment]
I'm analyzing blockchain for types of transaction. In this case output looks like a `p2sh` but output and input became `nonstandard`.

Actually your fix will help me to catch the `redeem.output is too short` error to mark transaction for example as `p2sh_irregular`.
