### ISSUE TITLE
get all inputs hash for signing from psbt

### ISSUE THREAD

**Issue by levischechter** [bitcoinjs/bitcoinjs-lib#1822]
hey team,
I'd be thrilled to see an example of how can i get the inputs hash that need to be signed from a psbt object.
Thanks in advance!

**Comment by motorina0** [comment]
You can check in `ts_src/transaction.ts` the methods [hashForSignature](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/ts_src/transaction.ts#L269) and [hashForWitnessV1](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/ts_src/transaction.ts#L345)

**Comment by levischechter** [comment]
@motorina0 thanks.
so i think my question is:
what are the params that i should pass to the functions?
and how do i know to which function should i call? - i assume i need to interpret the utxo but how?

**Comment by motorina0** [comment]
The params are defined right there, in the method definitio.

What exactly are you trying to accomplish?

Have also a look at the unit tests for some examples: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/transaction.spec.ts

**Comment by levischechter** [comment]
I want a flow such as:

- prepare a transaction in one place
- send hash for signing to another place
- retrieve the signature
- update the transaction in the first place
- broadcast the transaction

i got it all sorted out accept i don't know how to "extract" the hashes for signature

**Comment by motorina0** [comment]
If possible you should feed the signer a [psbt](https://github.com/bitcoin/bips/blob/master/bip-0174.mediawiki) and not just the message to be signed. This way the signer cannot be tricked into signing malicious messages (eg: a transaction that sends the funds to a different address)

If you still decide to go with the "message only" signing then there might be a (hackish) way:
 - the `signInput()` method of  `psbt` takes  a`Signer` instance
```ts
signInput(
    inputIndex: number,
    keyPair: Signer,
    sighashTypes?: number[],
  )
```
 - you can implement the `Signer` interface, but instead of signing, just store the message being signed (and produce a mocked signature)

```ts
interface Signer {
    publicKey: Buffer;
    network?: any;
    sign(hash: Buffer, lowR?: boolean): Buffer;
    signSchnorr?(hash: Buffer): Buffer;
    getPublicKey?(): Buffer;
}
```

 - then use the stored message/hash as you wish

**Comment by levischechter** [comment]
thank you so very much!
you helped me a lot!
have great day!
closing.
