### ISSUE TITLE
problem to use library and sub modules

### ISSUE THREAD

**Issue by stefanocudini** [bitcoinjs/bitcoinjs-lib#1823]
if you keep continuously changing the interfaces of the libraries on all next versions losing the backward compatibility this library becomes unusable outside the core maintainers.

it is practically impossible to find a working example online, all stackoverflow solutions break.

without clear documentation it is impossible to use.

I bring here an example: https://gist.github.com/assafshomer/89d72fae0de68689d9cc

**Comment by stefanocudini** [comment]
another example:
```js
const tx = new bitcoin.TransactionBuilder(network);
```
where is in last version TransactionBuilder??

**Comment by junderw** [comment]
> without clear documentation

- [CHANGELOG](https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.0.1/CHANGELOG.md)
- [EXAMPLES](https://github.com/bitcoinjs/bitcoinjs-lib/tree/v6.0.1#examples)
- [Tests filled with comments explaining various APIs](https://github.com/bitcoinjs/bitcoinjs-lib/tree/v6.0.1/test)

I think you meant to say "without documentation style *that I am used to reading*"

If you would like to include some sort of documentation style, we will review your PR and consider adding it in addition to the existing documentation.

> if you keep continuously changing the interfaces of the libraries on all next versions losing the backward compatibility this library becomes unusable outside the core maintainers.

- [Semantic Versioning](https://semver.org/)
  - When you npm install something it defaults to `^` which will never install a new major version without you explicitly installing it.
  - Old Stack Overflow solutions breaking is not a problem with the library. Using that logic, no library could ever perform a major update ever.

> I bring here an example:

Your example is 7 years old, and is easily found in our `Examples` in the `README` under [`Create (and broadcast via 3PBP) a Transaction with an OP_RETURN output`](https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.0.1/test/integration/transactions.spec.ts#L171-L200)

> where is in last version TransactionBuilder??

The last version with it was v5.2.0. (The previous major version) It was removed because the Psbt class is superior in every way.

---

I understand that some people believe that libraries should never make a breaking change ever.

Unfortunately, bitcoinjs does not subscribe to that idea.

If you use an old example from an outside source, you will need to check older versions (you can select tags on Github to explore older versions) for the APIs you want to use.

The better solution would be to search for an example on our Github, and if you don't find it, create an issue (without being rude) asking to add an example showing how to do something.

**Comment by michaelessiet** [comment]
@junderw Please is there documentation on how to send bitcoin from one address to the other without using transactionBuilder. I've been looking for one online for the past 2 days now and haven't found anything that actually works. They break one way or another

**Comment by junderw** [comment]
> @junderw Please is there documentation on how to send bitcoin from one address to the other without using transactionBuilder. I've been looking for one online for the past 2 days now and haven't found anything that actually works. They break one way or another

There is a whole list of examples in the README.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.1.0/test/integration/transactions.spec.ts#L86

**Comment by michaelessiet** [comment]
> > @junderw Please is there documentation on how to send bitcoin from one address to the other without using transactionBuilder. I've been looking for one online for the past 2 days now and haven't found anything that actually works. They break one way or another
> 
> There is a whole list of examples in the README.
> 
> [`v6.1.0`/test/integration/transactions.spec.ts#L86](https://github.com/bitcoinjs/bitcoinjs-lib/blob/v6.1.0/test/integration/transactions.spec.ts?rgh-link-date=2023-03-06T15%3A19%3A04Z#L86)

I noticed them but none are applicable to react native. Tiny-secp256k1 can't be used in react native due to it's use of 'fs'

**Comment by junderw** [comment]
> I noticed them but none are applicable to react native. Tiny-secp256k1 can't be used in react native due to it's use of 'fs'

You don't need to use tiny-secp256k1. There are alternatives.
