### ISSUE TITLE
How do I generate multiple Native SegWit (bech32) addresses from the same private key?

### ISSUE THREAD

**Issue by therapy** [bitcoinjs/bitcoinjs-lib#1828]
Hello, I'm currently building a web application and would like to achieve the following

1. Generate a private key, and store it in WIF form somewhere.
2. Using that private key, generate mulitple Native SegWit (bech32) addresses that can recieve bitcoin.

Can anyone help with this?

**Comment by Bzvwf16WSDKoSZd8** [comment]
Question 1:
```ts
import { ECPairFactory as ecpair } from 'ecpair'
import * as ecc from 'tiny-secp256k1'

let myKey = ecpair(ecc).makeRandom()
console.log(myKey.toWIF())
```
Question 2
```ts
import bitcoin from 'bitcoinjs-lib'
import { ECPairFactory as ecpair } from 'ecpair'
import * as ecc from 'tiny-secp256k1'
import { BIP32Factory as bip32 } from 'bip32'

let myKey = ecpair(ecc).makeRandom()

// Single private key
let { privateKey } = myKey

let root = bip32(ecc).fromSeed(privateKey)

// let child1 = root.derivePath('m/84'/0'/0'/0/0');
let child1 = root.deriveHardened(84).deriveHardened(0).deriveHardened(0).derive(0).derive(0)
// let child2 = root.derivePath('m/84'/0'/0'/0/1');
let child2 = root.deriveHardened(84).deriveHardened(0).deriveHardened(0).derive(0).derive(1)

console.log(bitcoin.payments.p2wpkh({ pubkey: child1.publicKey }).address) // Address 1
console.log(bitcoin.payments.p2wpkh({ pubkey: child2.publicKey }).address) // Address 2
```

**Comment by junderw** [comment]
Some notes:

1. Storing WIF individual private keys is no longer recommended.
2. Using a single private key as the seed for BIP32 is not a standard method of generating the seed, so you will need to remember this method (or preserve whatever source code you use) for as long as you maintain your wallet. It would be MUCH EASIER if you use the BIP39 library to generate a 12 or 24 word mnemonic phrase, and use that to instantiate the BIP32 HD wallet. (since this is the method that most wallet apps on the iOS/Android app store use, your mnemonic seed will be able to be recovered in existing apps for many many years to come.

**Comment by junderw** [comment]
1. It's highly recommended against making a web app for handling private key material. You should never send private keys to the server, and storing private keys in something like `localStorage` is also one XSS vulnerability away from leaking keys. It would be better to use some sort of native bundling solution to create a self contained app that has access to lower level secure storage in the OS. (keychain in macOS, for example)
2. If you want to store mnemonic phrase in a web app, it would be best to encrypt it using aes encryption after using some key stretching hash algorithm. ie. `key = pbkdf2("my password", "some salt", 32768, 32, "sha256")` then `encrypted = aes.encrypt(mnemonic, key)` and store the encrypted mnemonic... that way even if someone stole the localStorage contents they would need to keylog the password entry to decrypt it.
3. That said, this is still very insecure, and web wallets should make full use of CSP to try and remove any and all XSS risk they can.

> How do you think I should go about making sure that I generate a unique address?

BIP44/84/49 etc etc talk about gap limits in length. In general, you generate index 0-19, add them to an `unusedAddress` list. Then check the transaction history for all 20, find the latest index with a history, remove that address and all addresses before it. Then generate enough addresses to fill the list to 20 addresses again. Check the newly generated addresses for history, repeat.

This way, you will have 20 unused addresses with no history. Give the user the first address and more addresses if they ask.

You could also store the current index in localStorage etc.

When a user asks for a new address, generate the next index and count the index up 1.

**Comment by junderw** [comment]
This project is open source and you can make the payment page UI to fit any style you want (custom CSS)

https://btcpayserver.org/

You can even "create a store" using a Ledger or Trezor hardware wallet. (your server running BTCPay will automatically generate addresses from your wallet without needing private keys.)

---

For a store, if you want to create it yourself, you should generate the xpub (which is created using the last hardened derivation in your path ie. `root.deriveHardened(84).deriveHardened(0).deriveHardened(0).neutered().toBase58()`. It's called "xpub" because the string starts with xpub. xprv is private key)... then from the xpub you can create a bip32 node with fromBase58(xpub). Then derive the last 2 layers (non-hardened).

So you upload the xpub to the server, and everytime you generate an address and show it to a user, you store it in your database so you never use the same index again (don't show two invoices the same address ever)

Then you just make sure your derivation follows a common derivation pattern (like BIP84) and you should be able to manage those funds using most wallet apps.

I like BTCPay because it has a wallet UI (where you can connect Ledger/Trezor via USB) that also has access to the database so it knows exactly which addresses have balance or not.

**Comment by junderw** [comment]
Here's a video about BTCPay and how to set it up. (You can embed it into existing sites and it also has plugins for wordpress etc.)

https://www.youtube.com/watch?v=KqsM-n-e4aY

**Comment by junderw** [comment]
Note: in the video they discuss in length about Lightning node stuff, but just FYI lightning is not required to run BTCPay. The minimum you'll need is an xpub extended public key, or you can use Ledger/Trezor connect.

**Comment by junderw** [comment]
> Ideally not having to store previously used indexes.

You need to store state. There is no way around it.

If someone creates and invoice and never pays it, they now know an address and can mess with your store's accounting if you try to reuse the same address for another invoice.

The only way to keep track of invoices is to have a database with state.

Store the "last_used_index" on the database or something. Be sure to lock the database row when you select and update it to prevent race conditions.

> Also for clarification, only the second 0 (.derivePath("0/0")) should be modified is that correct?

Read BIP84. Yes, only the 2nd 0 should be incremented. 1/x is used for change addresses internal to the wallet.

**Comment by Bzvwf16WSDKoSZd8** [comment]
@therapy You should use WebSocket API to track address transactions. The mempool space api already have this function to use out of box.
[https://mempool.space/docs/api/websocket](url)

**Comment by SimonHausdorf** [comment]
> Here's the code for anyone reading this.
> 
> ```js
> // store this on server
> const xpub = root.derivePath("m/84'/0'/0'").toBase58();
> ```

Careful with this, it's not the xpub, it's the xpriv!
Should be replaced with
```js
const xpub = root.derivePath("m/84'/0'/0'").neutered().toBase58();
```

Also instead of using `.derivePath("0/0");` one can use `.derive(0).derive(1);`.
