### ISSUE TITLE
how to sign a transaction with an extended private key

### ISSUE THREAD

**Issue by zcaudate** [bitcoinjs/bitcoinjs-lib#1834]
I've looked at the tests here:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/test/integration/bip32.spec.ts

and I can generate an extended private key ie.  `xprv9s21ZrQH143K....`

however, I can't find any information on how signing a transaction works with the extended version of the private key.

are there any example code out there?

**Comment by junderw** [comment]
The Psbt signing methods (signInput, signAllInputs etc.) take a Signer interface. `ECPair` and `Bip32` both fill that interface, so you just need to derive the proper path and pass the result of derivePath to the sign method. ie.

https://github.com/bitcoinjs/bitcoinjs-lib/blob/2edfb992fa09761e09490b5efa27ba13a77de374/test/integration/transactions.spec.ts#L326-L358

Alternatively, if your Psbt has bip32DerivationPath info for each input, you can input the root extended private key into one of the signInputHD methods. (Since Bip32 implements the HDSigner interface)... but if you're not sure whether your Psbt will have derivation info or not, you'll have to derive the keys yourself.

**Comment by zcaudate** [comment]
@junderw thanks for that. I'll give it a go.
