### ISSUE TITLE
How to get the tx id and fee from a non finalized PSBT?

### ISSUE THREAD

**Issue by sebastianmontero** [bitcoinjs/bitcoinjs-lib#1842]
Is it possible to get the tx id and fee from a non finalized PSBT?

Thanks,

**Comment by junderw** [comment]
1. You can only get the txid from a non-finalized PSBT IF every input is segwit, and if any inputs are P2SH based segwit, it will be slightly difficult since you will need to place the redeemScript in the right place to get the txid to calculate properly.
2. Subtract the total output value from the total input value.

**Comment by sebastianmontero** [comment]
Thank you!
