### ISSUE TITLE
TypeError: Object.fromEntries is not a function

### ISSUE THREAD

**Issue by PRFinklemeister** [bitcoinjs/bitcoinjs-lib#1917]
Getting this error?

/node_modules/bitcoinjs-lib/src/crypto.js:52
const TAGGED_HASH_PREFIXES = Object.fromEntries(

TypeError: Object.fromEntries is not a function #1917

From this script:

```
const bitcoin = require('bitcoinjs-lib');
// generate a random private key
let private_key = bitcoin.ECPair.makeRandom();
// get the associated receive address
let receive_address = private_key.getAddress();
// print the address
console.log(receive_address);

```

**Comment by junderw** [comment]
That example code doesn't work with the current version of bitcoinjs-lib. You need to use v3.x.x which is many years old.

The error you get is because you are trying to load the latest version of bitcoinjs-lib with an old version of NodeJS that is not supported.

Your solutions are:

1. Use bitcoinjs-lib v3
2. Upgrade NodeJS to a more recent version with fromEntries, and change your example code to match. (See the README)
