### ISSUE TITLE
Can`t updateOutput, and missing fields, in psbt obj

### ISSUE THREAD

**Issue by ranmasootome** [bitcoinjs/bitcoinjs-lib#1938]
### **Cant update outout**

I'm trying to change the output, but I can't. output not updated

```js
const tx_size = psbt.__CACHE.__TX.virtualSize()
const fee = tx_size * feeRate
const self_return_value = psbt.txOutputs[psbt.txOutputs.length - 1].value

psbt.updateOutput(
    psbt.txOutputs.length - 1,
    { value: self_return_value - fee }
)
```

### **Missing fields, in psbt obj**

And I noticed that the inputs and outputs data is _not displayed/partially displayed_ in the "psbt.data" object. But all nice in _psbt.txInputs/psbt.data.globalMap.unsignedTx.tx.ins_ field

![image](https://github.com/bitcoinjs/bitcoinjs-lib/assets/136010062/89a272c5-e216-40dd-95ba-b3d242cbcf4e)

----

### **Is that how it should be?**

**Comment by junderw** [comment]
1. In the PSBT standard there are two places to insert data for each input and each output. You can think of them as "Input vs PsbtInput" and "Output vs PsbtOutput." You can not modify the Output, only the PsbtOutput. The Output contains the scriptPubkey and the value of the output. txOutputs is a read-only object that is created to let you peek into the state of the outputs, but you can not modify the Psbt's Outputs through it.
2. Yes, this is how it should be, since Psbts separate the Input and the PsbtInput. The psbt.data.inputs section only contains the PsbtInput data.
