### ISSUE TITLE
Need a local BTC node?

### ISSUE THREAD

**Issue by ruben2k1** [bitcoinjs/bitcoinjs-lib#1943]
I have a doubt, this library can make transfers and such without having a local Bitcoin node?

**Comment by junderw** [comment]
It doesn't need to be local, but you need a source for information. ie. Block explorers, Electrum servers, etc etc. Any sort of protocol where you could find information about UTXOs pertinent to your wallet.

Of course, it is recommended that you use your own node, otherwise the block explorer / electrum server etc etc could be lying to you.

BitcoinJS-lib does **not** sync blocks or receive transactions over the Bitcoin P2P network.
