### ISSUE TITLE
Transaction Version maxes out at the limits of signed 32 bit integers, but bitcoin's protocol takes uint32_t

### ISSUE THREAD

**Issue by Symphonic3** [bitcoinjs/bitcoinjs-lib#1964]
I am a bit confused as to whether this value should be interpreted as signed or unsigned. When creating a transaction with bitcoinjs, a version larger than 2147483647 or smaller than -2147483648 causes bitcoinjs' checkInt to throw a RangeError: "value" argument is out of bounds. However, in bitcoin, it seems as though these values should range from 0 to 4294967295. Curiously, positive values do line up properly with what other bitcoin implementations give.

**Comment by junderw** [comment]
https://github.com/bitcoin/bitcoin/blob/v25.0/src/primitives/transaction.h#L307

It is definitely a `int32_t`

And in `rust-bitcoin` (created by Core devs) it's i32

https://github.com/rust-bitcoin/rust-bitcoin/blob/bitcoin-0.30.1/bitcoin/src/blockdata/transaction.rs#L691

Out of curiosity, why exactly did you think otherwise?

**Comment by Symphonic3** [comment]
Ah, I may have looked too quick and confused it with nLocktime.
