### ISSUE TITLE
Check Input addresses signers

### ISSUE THREAD

**Issue by edsonPrimo** [bitcoinjs/bitcoinjs-lib#1985]
Is there any way to determine which addresses or public keys signed a transaction input using this library?
for example this testnet rawTransaction: 020000000001014a5401d1d7f96d7dcb4cf5549f381438982c73db735662f62a7869692d52585a0100000000fdffffff0264000000000000001976a9140a52370af52791198090b4d0afbea83c834a858e88ac740e000000000000220020311008a9d2275ca1e5323944e9fcfe5520cbd20a08f86c10f6c4c96d755f1ea904004730440220190f14639e256eafeff1cc77e81abc92dce69d25628158a0041f7e240afdbbe9022048e84397dbe9f5eba757051ab45fae942cfec8e7d01f4729128a9b457e6da8c50147304402206718187f1c5949edc77d0752da19bac8a0678979763074c2aa672c0ca82028de02200169232eed592aa505767b4700289ddd3b8d7af2d9d389fe5a1bb745f5c18ffd01475221031056e728c871f5209c5a914ef080a3a2b10a8325595675afdc82ebdfb90607502103ff278033706d581dcbfbc677732131af477df1f85a7687861f197dbfc318ccbc52ae1a3b2600

thanks!

**Comment by junderw** [comment]
There is no simple method call that will do that for you, but it is possible to work it out.

You would need to figure out the shape of each input by trying to load it into various Payment types through trial and error.

Then once you find the correct payment type you'd need to extract the signatures and pubkeys, then get the sighash for that input, then try verifying the signature with the sighash (message) and pubkey through trial and error until you find which one signed it.

This won't work for raw multisig though, since the pubkeys would be in the previous transaction's output.

**Comment by junderw** [comment]
It also won't work for super old P2PK signatures (since like raw multisig, the pubkeys go to the output), but that's just a single sig anyways so the question "which pubkey signed this" is an invalid question anyways so I didn't mention it.

**Comment by edsonPrimo** [comment]
@junderw, if I use the previous transaction, the one from which the input came, and load the output, would it be easier? If so, how can I do that?"

**Comment by junderw** [comment]
No, it won't be any easier. But it will allow you to detect raw multisig. (Which is rare, but I think one of those weird token protocols uses raw multisig in the output or something, so recently it has been popping up more recently)

**Comment by edsonPrimo** [comment]
Do you know of another library that would be more helpful? 
Any tips would be appreciated. Thanks again

**Comment by junderw** [comment]
> Any tips would be appreciated.

As I said before:

1. Use the payments API to find the shape of the inputs and witnesses via trial and error. (try-catch the exceptions thrown when you place an incorrect scriptSig and witness in the payment until you find a payment that matches) This should basically just be P2SH-Multisig, P2SH-P2WSH-Multisig and P2WSH-Multisig, since the only other alternative is raw Multisig, which requires the previous transaction's scriptPubkey (output script). So the only payments you should have to check are p2sh and p2wsh.
2. Once you find a Multisig and get the signatures and pubkeys, get the sighash from the transaction for that input. Depending on whether it's a P2SH-Multisig or not, the method you use changes since segwit v0 uses a different sighash algorithm. (for segwit you'll need the amount of satoshis that are spent in the input as well).
3. Take each pair of pubkey :: signature and verify the signature with the sighash. Then you'll find the pubkeys that signed.
