### ISSUE TITLE
Error when deserializing a PSBT

### ISSUE THREAD

**Issue by antondalgren** [bitcoinjs/bitcoinjs-lib#2114]
When trying to deserialize a PSBT that only has one output or one input defined crashes. 

See example below.

```typescript
import {Psbt} from "bitcoinjs-lib";

const psbt = new Psbt();
psbt.addOutput({
  address: "bc1qfxm76mpx6z8eg5jg2du2gr9020j27a94k8u7vx",
  value: 1,
})

const hex = psbt.toHex();
Psbt.fromHex(hex); // RangeError: Trying to access beyond buffer length
```

**Comment by jasonandjay** [comment]
![image](https://github.com/bitcoinjs/bitcoinjs-lib/assets/8192412/2ec6bdcf-7cd0-4b6f-9909-c7242dd87ac5)
After debugging, I found the reason
ParsePSBT will set vinLen to 1, but actual **no input**

**Comment by junderw** [comment]
Yeah. When parsing a transaction, a non-segwit tx with 1 output will have 0x00 and 0x01 for txinlen and txoutlen, and since the transaction parsing logic is matching on that specific pattern for segwit, there's really nothing we can do.

Solution: Don't make a Psbt with 1 output and 0 inputs.

**Comment by antondalgren** [comment]
Well... That's sad :( Thank you for taking the time to debug this for me. 

I guess it's not possible to differentiate a segwit transaction from a non-segwit transaction based on the bytes following `0x0001`?

One thing to add could be to throw an error when trying to serialize a non-segwit tx since it's not possible to deserialize it. It could be used to add context to why it's not possible to do that.

**Comment by junderw** [comment]
> Well... That's sad

We could probably create some sort of hack for Psbt specifically (since Psbt internal transactions have the invariant that they contain no input scripts or witnesses, so they would only be serialized as non-segwit), but it would increase complexity and add some invariants to the library in exchange for.......... what?

I don't understand the use case, so I'm comparing having to add something that is definitely annoying against losing the ability to make something that, as far as I know, no one needs.

**Comment by antondalgren** [comment]
Yeah, I understand you. I wouldn't like creating a hack either. Let's just leave this as is. 

Thanks!
