### ISSUE TITLE
Installation defaults to latest release candidate

### ISSUE THREAD

**Issue by landabaso** [bitcoinjs/bitcoinjs-lib#2176]
When running `npm install bitcoinjs-lib`, it defaults to installing the latest release candidate rather than the latest stable release.

Is this intentional, or was there perhaps a mix-up during the publishing process on npmjs? If this behavior is intentional, please close this issue. 👍

**Comment by junderw** [comment]
It was intentional insofar as I want people to try it, and anyone making an application will likely already have a major-locked dependency in their package file and shouldn't be affected.

It's only rc because I want to leave it open to make any breaking fixes. (The removal of Buffer and addition of ESM is a bit of a weird change and I forsee some weird bugs around there that require a breaking fix)
