### ISSUE TITLE
crypto-browserify dependency

### ISSUE THREAD

**Issue by STRML** [bitcoinjs/bitcoinjs-lib#345]
A call to `require('crypto')` inside browserify or webpack will automatically use the `crypto-browserify` package in the browser environment, and node `crypto` in Node.

Is there a reason to include this library? It causes large package bloat in Node projects.

**Comment by dcousens** [comment]
We were unable to release without including it because the main browserify was not using latest, or would resolve to an incompatible version of it.

**Comment by dcousens** [comment]
It could be removed now.

**Comment by STRML** [comment]
Thanks!

**Comment by dthorpe** [comment]
Just to clarify: a bitcoinjs-lib app built with browserify will still include crypto-browserify files, but just the ones provided by browserify itself?  This fix was to remove use of an additional crypto-browserify by bitcoinjs-lib that is no longer needed because browserify's built-ins are improved.

I'm still seeing a minimal bitcoinjs-lib app built with browserify that references crypto producing an output js of about 650k.  Is this the expected size (without js minification)?

Thanks

**Comment by dcousens** [comment]
@dthorpe this issue was based on the fact we previously had an inline dependency for `crypto-browserify` in the `package.json`, not the fact that the library can be browserified in general.
The reason for that was because we relied on the latest version of `crypto-browserify`.

A smaller (~303k) minimal bitcoinjs-lib build should now be possible with `1.5.6` (see https://github.com/bitcoinjs/bitcoinjs-lib/pull/376 for `1.5.x` release notes)
