### ISSUE TITLE
Add example on how to use a custom network

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#383]
Probably just need to outline something like the following:

``` javascript
var viacoin = {
  bip32: {
    public: 0x0488b21e,
    private: 0x0488ade4
  },
  dustThreshold: 560,
  feePerKb: 100000,
  magicPrefix: '\x18Viacoin Signed Message:\n',
  pubKeyHash: 0x47,
  scriptHash: 0x21,
  wif: 0xc7
}
```

The above is `1.5.x` compatible,  for `2.0.0` see [here](https://github.com/bitcoinjs/bitcoinjs-lib/issues/383#issuecomment-130850159).

**Comment by ricmoo** [comment]
Another useful note would be what fields are required for which parts of the library? For example, to just encode/decode from WIF, only *wif* is necessary.

There do not seem to exist BIP32 prefixes for Namecoin (although I have generated some that generate a prefix of **n**, if interested... Is this the right thing to do? Or just use bitcoin's?), but they can be simply omitted if you are not using HDNode.

It would be nice to know when defining custom networks what is required for my feature set.

**Comment by jprichardson** [comment]
@ricmoo regarding BIP32 prefixes for different coins, I wouldn't recommend doing so as it's pretty redundant (assuming you follow BIP44). See https://github.com/bitcoin/bips/blob/master/bip-0043.mediawiki#node-serialization for more detail. i.e. using `bitcoinjs-lib`with a custom network in most cases will require you making sure that you have the WIF version correct. Proof-of-stake coins do require different deserialization/serialization of transactions (due to the timestamp) - I'm working on a solution to address this, but it may be awhile.

**Comment by ricmoo** [comment]
Oh! That is PERFECT. I have been looking for that info documented somewhere. I noticed a few random alt-coins used their own prefixes.

Thanks. :)

**Comment by dcousens** [comment]
As of `2.0.0`,  the `network` type format would be aligned to this example:

``` javascript
  bitcoin: {
    messagePrefix: '\x18Bitcoin Signed Message:\n',
    bip32: {
      public: 0x0488b21e,
      private: 0x0488ade4
    },
    pubKeyHash: 0x00,
    scriptHash: 0x05,
    wif: 0x80,
    dustThreshold: 546
  },
```

**Comment by dcousens** [comment]
@jprichardson for what its worth,  you will still be required to specify the `network` object when calling `HDNode.fromBase58`,  as it will default to bitcoin otherwise.
