### ISSUE TITLE
Helloblock service is down,  switch integration tests blockchain provider

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#399]

**Comment by jprichardson** [comment]
Not sure if this is of any help... but it's working lovely as an HB replacement on my localhost: https://github.com/jprichardson/bitcoin-faucet

**Comment by jprichardson** [comment]
One of us could host one? Probably wanna add request restrictions. Doesn't Blocktrail have a faucet too?

**Comment by dcousens** [comment]
@jprichardson indeed block trail does have a faucet,  and that was my intention to switch to it.

**Comment by jprichardson** [comment]
:+1:

**Comment by weilu** [comment]
Sigh. This is fucked. cb-insight doesn't have `transaction.get` implemented. blockr keeps on giving me "Could not push your transaction!" "Did you sign your transaction?" =_=

**Comment by dcousens** [comment]
@weilu better off just using `cb-node` with https://www.blocktrail.com/, and using their faucet.

**Comment by dcousens** [comment]
@rubensayshi what is the best way we can get this into the travis testing cycle?

**Comment by weilu** [comment]
blocktrail requires an API token. puts me off

**Comment by jprichardson** [comment]
> blocktrail requires an API token. puts me off

@weilu it does me as well. That's why I don't use it.

**Comment by jprichardson** [comment]
> cb-insight doesn't have transaction.get

I'll merge/release right away if you submit a PR.

**Comment by rubensayshi** [comment]
could you explain me a little better why you're put off by the API key that's required to use the blocktrail API? you might be able to convince me to change it ;-0

and blocktrail implements the v0.2.1 cb API (https://github.com/blocktrail/cb-node/tree/blocktrail-v0.2.1) except for `Blocks.Get` gives 404 and `Transactions.Propagate` does not support more than 1 (because after discussing with @dcousens it made the error response very complicated)  
I'd implement v0.3.x too if you guys are satisfied with v0.3.2 and got cb-tester working for it....

**Comment by weilu** [comment]
Simple. I have nowhere to keep the key for the use case of a decentralized app, or in this case automated tests for an open source project. It's yet another account that I can do without.

**Comment by jprichardson** [comment]
> Simple. I have nowhere to keep the key for the use case of a decentralized app, or in this case automated tests for an open source project. It's yet another account that I can do without.

Agreed completely. Although @rubensayshi I completely respect your reasons for having a key - it just feels more apt for commercial level service.

**Comment by rubensayshi** [comment]
but you have to understand a little that to provide an API as a service that we need something to manage our customers a little etc.

Travis has a way to encrypt secret data such as API keys into the `travis.yml`, with the limit that it doesn't work for PRs (because someone doing a PR could just print the value as part of the PR)  
and I already suggested to @dcousens that I (or he) could create a seperate account with a seperate API key that is commited into the repo as fallback to the `travis.yml` one so even if someone is an ass and pushes it to the rate limit then it's only the tests for PRs that would suffer.  
We use this method for our own SDKs too (and I have my own API key in my `.bashrc` locally when I'm developing).

Alternatively I could allow API access without an API key and when no API key is proveded limit by IP with limits similar to our free tier (or lower), the API keys don't prevent abuse much anyway because there's already ppl who create multiple accounts and rotate API keys xD

**Comment by weilu** [comment]
I'm of the opinion that nobody should suffer if he/she wants to make a PR; everybody should be able to run integration tests locally without having to create any account on any website. The contribution barrier should be as low as it can possibly get. 

It's your API so it's up to you. bitcoinjs-lib doesn't __need__ it one way or another. My personal suggestion is that since you'll have to implement IP based rate limiting anyway, might as well do it sooner and drop the API key requirement, for the sake of good causes like open source and decentralized apps.

**Comment by rubensayshi** [comment]
like I said, you could just commit an API key of a free account so that anyone can run the code, as long as you don't have a bad actor who thinks it's fun to take the API key and hammer it so it's constantly on the rate limit.

It's still on the trello board to discuss if we want to enable API-key-less access (I personally want to, because it also lowers the barier to entry for people to copy, paste & run example snippets etc), I'll bump it up :)

**Comment by smithb1994** [comment]
I don't like the idea of API keys... I believe https://blockr.io has everything we need.

**Comment by weilu** [comment]
> as long as you don't have a bad actor who thinks it's fun to take the API key and hammer it so it's constantly on the rate limit

That's the assumption I'm reluctant to believe. Fun or troll doesn't even have to the motivation -- it's just easier to use an existing key out there available, than to register an account of your own. If you have to resolve to making an API key that's meant to be private public, there's no point having it to begin with.

I look forward to a keyless version of blocktrail :)
