### ISSUE TITLE
ECPair not in 1.5.7 in case anyone else spent hours figuring that out

### ISSUE THREAD

**Issue by smithb1994** [bitcoinjs/bitcoinjs-lib#408]
The the most current npm module is running 1.5.7 which does not have ECPair in it. Just giving anyone else a heads up, in case they were having the same problem. 

Is the master branch stable enough to push to npm, to avoid the confusion?

**Comment by jprichardson** [comment]
The master branch is for version `2.0` (https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/package.json#L3)

**Comment by smithb1994** [comment]
Guestimated release date?

**Comment by dcousens** [comment]
@smithb1994 there a few things that still need to be done.  See the 2.0.0 milestone.  Once they are complete,  2.0.0 will be published.

At this time,  I just haven't had time to finish it.  Yet.

**Comment by dcousens** [comment]
Will close this on 2.0.0 being published.

**Comment by dcousens** [comment]
@jprichardson maybe having `2.0.0` in master before being published is just a straight up bad idea.  Thoughts?

**Comment by jprichardson** [comment]
Yes, I think `2.0.0` should have its own branch and `master` should represent the stable/production release build. Perhaps we should loosely adopt gitflow conventions? At this moment could be as simple as just two branches `master` and `2.0.0`. Thoughts?

**Comment by smithb1994** [comment]
Yes please... Not sure what the benefit is, of having dev-branch on master.

**Comment by weilu** [comment]
I don't think there's anything wrong with having master as the dev branch -- in this case, I wonder if @smithb1994 would even be aware of the existence of `ECPair` until 2.0 comes out. IMHO the more people we can get to test things out and give feedback, the more robust the stable versions will be. 

To solve the issue @smithb1994 has, solution 1: @smithb1994 can consider put more trust on the readme in his/her node_modules folder rather than whatever is on github. 2: we link release notes on readme, and enlarge the font of the section that says "master is our development branch"

**Comment by dcousens** [comment]
@smithb1994 it allows users who want to use the latest to easily see changes and for the general public to see that we are in active development.

It is a practice assumed by most projects,  however larger projects that might have run into this issue have probably linked to documentation **off** GitHub, and therefore don't have this issue (directly anyway).
