### ISSUE TITLE
Review #411 reaching undefined signatures

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#415]
As seen in #411,  we are somehow getting `signature === undefined` from `TransactionBuilder.prototype.fromTransaction`. 

Although the PR fixed the issue,  it is still something that should either fail during importing or handle it properly.

Needs review.

([relevant code](https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L56-L72))

**Comment by rubensayshi** [comment]
in my case (and the test case I added in #411) the problem occurs because the partially signed TX originates from a non-so-perfect implementation (in my case, that's bitcoinjs-lib 1.4.1), but it's simply fixable by rearranging the signatures.

I'd strongly prefer it to *just work* instead of throwing errors, because then I'd need code to go and fix it ...

**Comment by dcousens** [comment]
This behaviour is now sane,  `undefined` is now the default state for all `signatures` in `TransactionBuilder`,  and if `pubKeys.length` !== `signature.length`, then something is wrong.
As before,  `signatures` itself won't always exist unless the `scriptType` is supported.
