### ISSUE TITLE
How do I get privatekey (hex) from randomly generated key?

### ISSUE THREAD

**Issue by smithb1994** [bitcoinjs/bitcoinjs-lib#416]
I've been looking through the tests and I can't find out how to do it.
Here's what I have:

```javascript
var bjs = require('bitcoinjs-lib'); //dev version

var keyPair = bjs.ECPair.makeRandom();
var address = keyPair.getAddress().toString();
console.log(address);
```

I get the address, but I want to get a private key in hex somehow from "keyPair".
Thanks.

**Comment by dcousens** [comment]
You can't really get the `hex` of a Bitcoin private key, because it needs to be represented in a custom format (known as WIF) to ensure the compression information is not lost.

The WIF format is by definition `base58`,  however,  you could use the `bs58check` module to decode it and retrieve the private key in hex format. 

`base58check.decode(bjs.ECPair.makeRandom().toWIF()).toString('hex')` would work.

**Comment by dcousens** [comment]
Perhaps we could add an encoding parameter for `toWIF` that allowed you to avoid the `bs58check` encoding initially?
@jprichardson thoughts?

**Comment by smithb1994** [comment]
Thanks, WIF works for what I needed.

**Comment by jprichardson** [comment]
> Perhaps we could add an encoding parameter for toWIF that allowed you to avoid the bs58check encoding entirely?

Why would we want to do that? What would be the use case?

**Comment by dcousens** [comment]
@jprichardson well,  it is something that other libraries offer.  I personally have never seen a use case for it.
If @smithb1994 actually needed it,  I might have considered it,  but it seems the alternative of not providing it has provided a better solution for him anyway.

**Comment by afk11** [comment]
@youssefgh when you decode the WIF, you get an ECPair. If you do getPublicKeyBuffer(), you can make the public key hash `bitcoin.crypto.hash160(pubKeyBuffer)` and use script templates to obtain the output script you want. `bitcoin.script.witnessPubKeyHash.output.encode(hash)`
Then, pass the output script to `bitcoin.address.fromOutputScript(script)`

**Comment by youssefgh** [comment]
@afk11 i already can create P2SH(P2WPKH) and native P2WPKH and retrieve there private key using : `Wif.decode(ecPair.toWIF()).privateKey`
But since WIF is used as an export format for P2PKH addresses (am not sure though) it will be weird to go through WIF just to get the private key for P2SH(P2WPKH) and P2WPKH
Please correct me if am wrong, and i appreciate taking the time to write me the detailed explanation above

**Comment by dcousens** [comment]
> But since WIF is used as an export format for P2PKH addresses

That is not true.

> Wallet Import Format (WIF, also known as Wallet Export Format) is a way of encoding a private ECDSA key so as to make it easier to copy.

**Comment by youssefgh** [comment]
Thanks a lot @dcousens for the correction !
