### ISSUE TITLE
Uglify instructions not clear

### ISSUE THREAD

**Issue by devluxg** [bitcoinjs/bitcoinjs-lib#555]
Hello,

In your README it says...

> NOTE: When uglifying the javascript, you must exclude the following variable names from being mangled: Array, BigInteger, Boolean, Buffer, ECPair, Function, Number, Point and Script. This is because of the function-name-duck-typing used in typeforce.

I've googled the matter and I don't find any reference on how to do this.  Can you possibly elaborate on this a bit further?  Thanks!

**Comment by dcousens** [comment]
It is left as a generalized statement due to their being different implementations and methods of "uglifying" your Javascript,  however I'm always open to maybe changing it to be more specific.

Using `uglifyJS` by `mishoo` (https://github.com/mishoo/UglifyJS2) see `--reserved`

Example:
``` bash
uglifyjs ... -m -r 'Array,BigInteger,Boolean,Buffer,ECPair,Function,Number,Point'
```

`Script` is no longer needed.
