### ISSUE TITLE
Can I use bitcoinjs to authenticate with bitid?

### ISSUE THREAD

**Issue by dicoy** [bitcoinjs/bitcoinjs-lib#566]

**Comment by coreyphillips** [comment]
Yes, but you will also need bitcoinjs-message located here (https://github.com/bitcoinjs/bitcoinjs-message) to create the signature.

I've successfully implemented bitcoinjs-lib and bitcoinjs-message for use with BitId in a react native app so that's what I'll use as the example. The implementation is pretty straight forward and summed up below:
```
var msgkeyPair = bitcoin.ECPair.fromWIF(privkey);
var message = uri;
var signature = bitcoinMessage.sign(msgkeyPair, message);
var signature = signature.toString('base64');
fetch(url, {
  method: "POST",
  headers: {'Accept': 'application/json', 'Content-Type': 'application/json'},
  body: JSON.stringify({uri: uri, address: address, signature: signature})
})
```

The best example I could find for the callback format is located here (https://docs.google.com/presentation/d/19iODrgKsVigsA17csNF3HU75UG9eiI5Z6cX2OczvIsw/pub?slide=id.g12ca75bea_0117) from the BitId docs. Hopefully this helps.

**Comment by dcousens** [comment]
Thanks @coreyphillips!

Interesting to see you are using `bitcoinjs-message` already,  since it won't be deprecated from `bitcoinjs-lib` until `3.0.0`,  but good work!

**Comment by coreyphillips** [comment]
I saw that bitcoinjs-message was being separated from bitcoinjs-lib so figured I would try to get ahead it. Didn't realize it wasn't being deprecated until 3.0.0. That's good to know. Thanks!

**Comment by dcousens** [comment]
@coreyphillips let me know if I can make https://github.com/bitcoinjs/bitcoinjs-lib/issues/508 any clearer. :)
