### ISSUE TITLE
Where is the details of the Api

### ISSUE THREAD

**Issue by stylehuan** [bitcoinjs/bitcoinjs-lib#585]
Where is the details of the Api

**Comment by dcousens** [comment]
Related
* https://github.com/bitcoinjs/bitcoinjs-lib/issues/569
* https://github.com/bitcoinjs/bitcoinjs-lib/issues/500

Master issue: https://github.com/bitcoinjs/bitcoinjs-lib/issues/272

**Comment by stylehuan** [comment]
@dcousens  tanks!  But I am don't fully understand what's the difference between ‘bitcoinjs-lib’ and 'bitcore'

**Comment by stylehuan** [comment]
I want to use bitcoinjs,but I don't know how to start
![image](https://cloud.githubusercontent.com/assets/6212099/15984015/3a3550bc-2fee-11e6-8d6d-3f2b2c89ad0c.png)

`makeRandom`  from `ECPair`.  so，What attributes and methods from `ecpair`,I can't find it.

**Comment by jprichardson** [comment]
Until we can improve the documentation, here is `ECPair`:

https://github.com/bitcoinjs/bitcoinjs-lib/blob/v2.2.0/src/ecpair.js

I also suggest browsing through the following:

https://github.com/bitcoinjs/bitcoinjs-lib/tree/v2.2.0#examples

**Comment by dcousens** [comment]
@stylehuan I assume you figured out what you needed?

**Comment by mehranrasulian** [comment]
Where is the documentation for this library? how these 2000 people stared this lib are working with it???

I looked at some basic examples but they really confused me!!
You have written a really good lib (as blockchain.info is using it) but wasn't it better to write less code and more docs? just to be a more popular lib (As this is the first reason for most open source projects).

I want to start creating a wallet with some addresses, and doing a transaction at the end for the begin. But really don't know how and where to start, so I think it's better to start with another lib that has a document, since it seems that bitcoinjs is for experienced bitcoin developers than a beginner.

**Comment by dcousens** [comment]
@mehranrasulian I wouldn't say `bitcoinjs-lib` is aimed at beginners to Bitcoin.
They would probably be a liability to themselves.

If you can ascertain a minor understanding of Bitcoin fundamentals, and some of the terminology involved,  then the examples should be clear. 

If you had any specific questions or ways we could improve the examples,  we'd be happy to help!
