### ISSUE TITLE
Uncompressed keys considered non-standard in witness scripts

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#641]
Reference: https://bitcoincore.org/en/meetings/2016/09/29/

Relevant code: https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/script.js#L134-L147,  and subsequently all scripts that function use it would need to know they are in a `SegWit` context.

**Comment by dcousens** [comment]
So, `function isPubKeyHashInput (script) {` would probably become `function isPubKeyHashInput (script, inWitness) {` or some such.

**Comment by dcousens** [comment]
As mentioned in https://github.com/bitcoin/bips/pull/459/files#diff-d6a595a37a5d316054e79e53e9c2382fR128

**Comment by afk11** [comment]
Not easy currently, but did something recently lead me to something that could help. Maybe adding some state to the script object: no state means it behaves like a scriptPubKey, and otherwise, it can be in a P2SH state, a P2WSH state, or a P2SH+P2WSH state.

Allowed state transitions:
```
none -> p2wsh
p2wsh -> p2sh
none -> p2sh
```

Forbidden:
```
p2sh -> p2wsh (p2sh happens after p2wsh, so this wouldn't work)
p2sh -> p2sh (nesting forbidden)
p2wsh -> p2wsh (nesting forbidden)
none -> p2wsh IF THE SCRIPT HAS UNCOMPRESSED KEYS
```

Mutating a script with `P2WSH()` would cause it to check the pubkeys and maybe other details (nesting). NB for later, going from P2WSH -> P2SH should mean the actual script is replaced with it's witness program.*

It might help us in other ways - you could expose `getScriptHash` and `getWitnessScriptHash` functions (opportunity to cache also). After making it P2SH, you'd replace getWitnessScriptHash with a function causing an error (cos P2SH scripts can't have a P2WSH output script)

This is only necessary because `script.scriptHash.output.encode()` etc take hashes (as they should) so there's no opportunity to check what we're hashing.. unless we offer an API that allows it :) 

When I was working on this I didn't really think about the uncompressed issue, though it seems to work ok.

What this would hopefully give us: people only use script output templates for the raw script, and decorate those scripts with contextual behavior. It's probably easier to use than calling the script templates by hand..

```js
var raw = script.multisig.output.encode(2, [])
var ws = p2wsh(raw)
var rs = p2sh(ws); // See note at *, replace witness script to witness program
var spk = rs.getOutputScript()
```

**Comment by afk11** [comment]
bugger, all that is useless if they do P2WSH|P2PKH..

**Comment by dcousens** [comment]
We should add a check at https://github.com/bitcoinjs/bitcoinjs-lib/blob/master/src/transaction_builder.js#L105 ?

**Comment by dcousens** [comment]
Even a length check on that line would be better than not?

**Comment by afk11** [comment]
Agreed, think this is a reasonable catch-all for it. Ideally it would be impossible to produce these addresses.

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/pull/857
