### ISSUE TITLE
SegWit: the TransactionBuilder API

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#695]
Just a dumping ground for thoughts in regard to the TransactionBuilder and segregated witness support

**Comment by afk11** [comment]
There seems to be this kind of motif throughout working a segwit transaction, whether it's extracting signatures, signing, or serializing them. 

I try to keep 'stuff' general, so `extractSigsFromChunks(type, chunks)` is there to handle regular scriptSigs [decompiled], or P2SH script sigs [decompiled], witnesses [they already are an array!]

```
var SIGNABLE_SCRIPTS = [bscript.types.P2PK, bscript.types.P2PKH, bscript.types.MULTISIG]
var type = bscript.classifyOutput(prevOutScript)
if (SIGNABLE_SCRIPTS.indexOf(type)) {
  // do stuff
}

if (type === bscript.types.P2SH) {
  // take redeemScript, and doStuff with it instead
  // set type to redeemScriptType
}

if (type === bscript.types.P2WPKH) {
  // do stuff, by generating the p2pkh scriptCode in situ
} else if (type === bscript.types.P2WSH) {
  // take witnessScript, and doStuff with it
  // set type to witnessScriptType
}

if (SIGNABLE_SCRIPTS.indexOf(type)) {
  // it worked
}
```

**Comment by afk11** [comment]
As you can see, this relies on knowing what prevOutScript is. I dislike coming up with this by inspecting the scriptSig. With the right data it should be able to keep you safe, not help you do silly things. 

That opinion aside, the library needs the scriptPubKey, and the value if the scriptPubKey (directly or by P2SH) uses segwit. With that, I suggest we pass the full txOut field in going forward. It's a break, lets make it worthwhile. 

Next part: redeem & witness scripts. With the full txOut field, we can now decide whether to accept or reject any attempted P2SH or P2WSH scripts. This is probably saner than deciding on the presence of a redeemScript, or all else, assume P2PKH. 

With the txOut, redeemScript, and witnessScript all referencing eachother, you can now encode/decode any scriptSig / witness, and verify signatures. We want to reach this state before we attempt to sign.  We also need the txOut & redeemScript/witnessScript/sigVersion around just to parse partially-signed multisigs.

So, lets fail hard if the correct conditions aren't met to sign an input. 
 - (tx, nIn, txOut) are now required, optionally including options with redeemScript / witnessScript
 - txOut is checked against redeemScript and witnessScript. save them all for later.
 - extract signatures, checking the embedded redeem & witness scripts against the ones we know are correct.
 - at this point the caller can sign (key, hashType)
 - we can deserialize, because we have the txOut and know what script type to use.

**Comment by afk11** [comment]
I've some of this already done in a branch: https://github.com/afk11/bitcoinjs-lib/blob/2cb37a24a4f1877d689976ce04440f49ded11c87/src/transaction_signer.js

I won't be rebasing it, so much has changed, and I'm rewriting meanwhile.  You'll see the motif I mentioned earlier come up a lot, so my rewrite saves the results of `solve` for the scriptPubKey, redeemScript, witnessScript, so it can deduce rather than parse/check redeemScripts every time.

**Comment by afk11** [comment]
It might be good to think about handling other script types so we can accommodate them later. Eg, signing a script with CSV. maybe we should accept the current block height/time so the signer can see if it can currently sign? 

What other things might we have to work with forward?

**Comment by dcousens** [comment]
As discussed on slack,  here are the considerations for the `TransactionBuilder` API.


# Positional argument headaches, maximum 2.0.0 compatibility
## Specification
addInput (txHash, vout[, sequence, prevOutScript])
addInput (prevTx, vout[, sequence])
sign (vin, keyPair[, redeemScript, hashType, witnessScript, value])

## Examples
p2pkh:    addInput('00000....', 0)
        sign(0, keyPair)

p2sh:    addInput('00000....', 0)
        sign(0, keyPair, redeemScript)

p2wpk:    addInput('00000....', 0, prevOutScript)
        sign(0, keyPair, , , , value)

p2wsh:    addInput('00000....', 0, prevOutScript)
        sign(0, keyPair, , , witnessScript, value)

p2sh(p2wpkh):    addInput('00000....', 0)
                sign(0, keyPair, redeemScript, , , value)

p2sh(p2wsh):    addInput('00000....', 0)
                sign(0, keyPair, redeemScript, , witnessScript, value)




# redeemScript Array (MAST friendly?)
## Specification
addInput (txHash, vout[, sequence, prevOutScript])
addInput (prevTx, vout[, sequence])
sign (vin, keyPair[, redeemScript || [redeemScript], hashType, value])

## Examples
p2pkh:    addInput('00000....', 0)
        sign(0, keyPair)

p2sh:    addInput('00000....', 0)
        sign(0, keyPair, redeemScript)

p2wpk:    addInput('00000....', 0, prevOutScript)
        sign(0, keyPair, , , , value)

p2wsh:    addInput('00000....', 0, prevOutScript)
        sign(0, keyPair, , , witnessScript, value)

p2sh(p2wpkh):    addInput('00000....', 0)
                sign(0, keyPair, redeemScript, , value)

p2sh(p2wsh):    addInput('00000....', 0)
                sign(0, keyPair, [redeemScript, witnessScript], , value)




# Options arguments
## Specification
addInput (txHash, vout[, optionsA])
sign (vin, keyPair[, optionsB])

where

optionsA: { sequence, prevOutScript }
optionsB: { redeemScript, hashType, witnessScript, value }

## Examples
p2pkh:    addInput('00000....', 0)
        sign(0, keyPair)

p2sh:    addInput('00000....', 0)
        sign(0, keyPair, { redeemScript })

p2wpk:    addInput('00000....', 0, { prevOutScript, value })
        sign(0, keyPair)

p2wsh:    addInput('00000....', 0, { prevOutScript, value })
        sign(0, keyPair, witnessScript)

p2sh(p2wpkh):    addInput('00000....', 0)
                sign(0, keyPair, { redeemScript, value })

p2sh(p2wsh):        addInput('00000....', 0)
                sign(0, keyPair, { redeemScript, witnessScript, value })











# Options arguments (simplified)
## Specification
addInput (txHash, vout, sequence)
sign (vin, keyPair[, options])

where

options: { redeemScript, hashType, witnessScript, value }

## Examples
p2pkh:    addInput('00000....', 0)
        sign(0, keyPair)

p2sh:    addInput('00000....', 0)
        sign(0, keyPair, { redeemScript })

p2wpk:    addInput('00000....', 0)
        sign(0, keyPair, { value })

p2wsh:    addInput('00000....', 0)
        sign(0, keyPair, { witnessScript, value })

p2sh(p2wpkh):    addInput('00000....', 0)
                sign(0, keyPair, { redeemScript, value })

p2sh(p2wsh):        addInput('00000....', 0)
                sign(0, keyPair, { redeemScript, witnessScript, value })







# Options arguments (txOut & array, MAST friendly?)
## Specification
addInput (txHash, vout, sequence)
sign (vin, keyPair[, options])

where

options: { txOut, redeemScripts, hashType }
txOut: { script, value }

## Examples
p2pkh:    addInput('00000....', 0)
        sign(0, keyPair)

p2sh:    addInput('00000....', 0)
        sign(0, keyPair, { redeemScript })

p2wpk:    addInput('00000....', 0)
        sign(0, keyPair, { txOut })

p2wsh:    addInput('00000....', 0)
        sign(0, keyPair, { redeemScript, txOut })

p2sh(p2wpkh):    addInput('00000....', 0)
                sign(0, keyPair, { redeemScript, txOut })

p2sh(p2wsh):        addInput('00000....', 0)
                sign(0, keyPair, { redeemScript(s), txOut }) (edited)

**Comment by afk11** [comment]
Witness signer: WIP as it's been rewritten a good few times https://github.com/bitcoinjs/bitcoinjs-lib/compare/witnesshash...solve-witness-signer?expand=1

**Comment by afk11** [comment]
`options` shouldn't contain sigHashType, since that's decided per-signature.

**Comment by dcousens** [comment]
> Value isn't always required, seems a waste to have txOut..

Unless we make it so.
`.fee()` would be a fantastic thing to have!
And actual reliable fee safety would be great too.

Do I think we should provide an unsafe option for those who know what they're doing?  Yes. 
But,  we can certainly improve the default.

**Comment by afk11** [comment]
That's a possibility, wonder what else we could pack into opts? 

Could define criteria the signer needs before it will even think of signing, and supplement some details to let other checks take place? Eg, perhaps providing an inputs prevTx is sufficient to get the txOut script/value, aiding in signing/verification and also for fee's as you describe?

**Comment by afk11** [comment]
https://github.com/bitcoinjs/bitcoinjs-lib/pull/746 segwit signer without any other break

**Comment by dcousens** [comment]
- [ ] `Transaction.prototype.addInput` w/ options object

**Comment by afk11** [comment]
* do we separate transaction building and transaction signing?
 * require txOut in order to sign an input
 * can we make it so an input is only expanded once the user has requested it? Imagine that no inputs are classified/etc unless the user calls sign()
 * see 3: a method to create an input signer object from nIn, txOut, [rs], [ws]. this essentially classifies the input, connects all the scripts together, and decides if it can sign this (after pruning away all the p2sh/p2wsh stuff and looking at the scripts)
 * operations & state now appropriately scoped onto a Checksig object, we can store keys/sigs separately, and have an array, inputSigner.steps
 * dealing with multiple Checksig operations in a script. Eg, `Checksig:[P2PKH - verify,Alice] Checksig[P2PKH, Bob]` requires new function `inputSigner.signStep(idx, key, hashType)`, implicitly idx is always 0 currently, but one advancement here is that we have many Checksig operations, with different keys/keyHashes (now have an array inputSigner.steps)
 * Even with an array of steps, their order or sequence or activation is not conditional, unless we support scripts with IF's in them. Supporting IF's means dynamically populating the inputSigner.steps array with Checksig / Conditionals that are exclusive to one of the n pathways the script can take during execution. 
 * Dealing with conditionals (non-breaking public change, just code for parsing logical pathways and another parameter on the signing options object `logicalPath`)

**Comment by afk11** [comment]
I wrote up this spec for signing and scoping data into a clean API here: https://gist.github.com/afk11/ab3b303f46f3707b308a6c2dd57ac52c It needs some updating to better describe conditionals and `*VERIFY` ops

**Comment by dcousens** [comment]
Closing,  I don't think `TransactionBuilder` should continue to grow in complexity.
I think combined with what we have in https://github.com/bitcoinjs/playground - if we find some abstraction that can sign those representations for us... we'll be laughing.

@afk11 it'd be good if we can tee up a call within a week or two to discuss this,  I know you've put a lot of effort into the `TxSigner`,  and I'd love to hear your opinion on how this will mesh.
