### ISSUE TITLE
SegWit: script templates API

### ISSUE THREAD

**Issue by dcousens** [bitcoinjs/bitcoinjs-lib#707]
Thoughts on:

* `scripts.witness.scripthash.output.encode` rather than `scripts.witnessscripthash.output.encode`

and maybe something like

* `scripts.witness.scripthash.stack.encode(buffers, witnessProgram)`?

**Comment by afk11** [comment]
`script.witness.scripthash.output.encode` :+1: 
not sure about the scripthash stack, since technically you can just do `buffers.push(witnessScript)` and the witness is fully formed. 

https://github.com/bitcoinjs/bitcoinjs-lib/compare/witnesshash...solve-witness-signer?expand=1#diff-a134c9a7b159e0c41466b5c1f269a6a1R393

**Comment by dcousens** [comment]
@afk11 I know.
Maybe it isn't worth encapsulating.
