### ISSUE TITLE
Import address to bitcoin-core wallet

### ISSUE THREAD

**Issue by boosth** [bitcoinjs/bitcoinjs-lib#714]
Sorry if this is dense but is there a trick to assigning a transaction to specific wallet with bitcoinjs?

ex. If I have a full node running can bitcoinjs create an address what will be attached to a wallet on that node?

**Comment by dcousens** [comment]
https://bitcoin.org/en/developer-reference#importprivkey might be what you are after.

**Comment by boosth** [comment]
Thanks for this information.  Is this an appropriate method or is there another option using bitcoinjs directly?

1: Create address with bitcoinjs
2: Save address to local db
3: Wait for transaction confirmation/verification ex notification from blockchain.info
4: Import address to local wallet via backend script

**Comment by dcousens** [comment]
@boosth of course,  the steps you out line are fine if you happy to trust blockchain.info instead of your own full node.

**1: Create address with bitcoinjs**
2: Save address to local db
3: Wait for transaction confirmation/verification ex notification from blockchain.info

The bolded step is the only step that `bitcoinjs-lib` performs however.
