### ISSUE TITLE
How to encrypt data and decrypt data?

### ISSUE THREAD

**Issue by namuyan** [bitcoinjs/bitcoinjs-lib#782]
I want to make a system.

1. Person A want to send message with encrypted to person B.
2. Person A encrypt data by B's address (or by pubkey?).
3. Person B decrypt encrypted data by B's Privatekey.

How to encrypt and decrypt function?

**Comment by afk11** [comment]
Hi, and welcome! 

This is a bitcoin library, and although the internals deal with public key cryptography, you won't find many of the things you need to actually build a secure encrypted messaging protocol. 

I would suggest just taking existing software and using it - deploying your own just isn't a good idea - but if it's just for learning: you need a general purpose crypto library, and probably want to read up on existing protocols. 

That said, I do think this issue is off-topic here.

**Comment by namuyan** [comment]
Thank you for reply!
I try to use already exist ways with RSA !
