### ISSUE TITLE
P2SH input marked as `nonstandard` when TransactionBuilder.fromTransaction is called on an unsigned Transaction object

### ISSUE THREAD

**Issue by Melvillian** [bitcoinjs/bitcoinjs-lib#835]
Our architecture creates an unsigned txn on the server, and then sends it to the client for signing. This means `buildIncomplete` is called on the server, and then the resulting `Transaction` is serialized by calling `toHex` and sent to the client. Since the transaction has no signatures, it also has no scriptsig, and thus the `script` field of the input gets set to the 0 byte. Later on when the client goes to reconstruct the `TransactionBuilder` from the txn hex, it marks the input as `nonstandard` because it sees the 0 byte `script` field and doesn't know what to make of it.

```
const bitcoin = require('bitcoinjs-lib');
const txHex = '01000000017cd3e13955ca0d530f475e57e18d3f4ceccaf23a4ebaffa0deb0b390780585c0000000000100ffffffff0200c2eb0b0000000017a9142888259060d075b21d461632d0b265ad7ca401c58784f6ae2f0000000017a9146f0cd2b904d634f3c6266a715b017ed943e4572b8700000000';
const tx = bitcoin.Transaction.fromHex(txHex);
const txBuilder = bitcoin.TransactionBuilder.fromTransaction(tx, bitcoin.networks.testnet);
```

See the inspection screenshot below for what the TransactionBuilder considers the type of prevOutType to be:

![image](https://user-images.githubusercontent.com/1884338/28889772-f94aecae-7779-11e7-8a91-dd3609b26ea2.png)

Later on, when the client goes to sign the Transaction's single input, it fails with a `Error: PrevOutScript must be P2SH` because `prevOutType` is `nonstandard`.

Is this a bug? I know it's correctly marking it as 'nonstandard' because of the input's `script` value, but it seems incorrect that the fact that the input is a P2SH input relies on the fact that a proper scriptSig is set on the input. This makes our architecture (server creates unsigned tx, sends it to client for signing) more complex because now the client needs to scrap the txn's input and remake them with the proper `script` value.

Is there a better approach to solving this problem?

**Comment by afk11** [comment]
I wrote some of this code, so taking an interest in bugs around this area. If you aren't providing (1) the redeemScript or even at worst (2) the scriptPubKey, the library can't classify your transaction - and if it can't classify it, it should fail when you ask it to sign. 

> because now the client needs to scrap the txn's input and remake them with the proper script value.

I think this might work: server sets sig: `OP_0 [redeemScript]`. For now, signScript would only be updated when you call `sign`, because by then you'd pass the redeemscript in.

Attempting to classify against an `input.script` should generally be discouraged and I eventually will be working towards this. It completely fails with examples like `[PUBKEY] CHECKSIGVERIFY TRUE` (if you looked at `input.script: <sig>` you might assume it's P2PK, but it's a very different output script. 

I'd rather instead of all this happening during `sign`, there be some step beforehand that involves giving the TransactionBuilder the redeemScript/scriptPubKey/witnessScript/witnessValue, where you are actively (and forced to) provide everything needed to classify the input (and determine signScript) You could call sign on the resulting object, even expose a verification function.. A task for another day unfortunately, since it calls for a BC break.
