### ISSUE TITLE
BIP 112 Support (CSV)

### ISSUE THREAD

**Issue by colatkinson** [bitcoinjs/bitcoinjs-lib#923]
I notice that there is no explicit `OP_CHECKSEQUENCEVERIFY` support. While scripts using this operation can still be constructed by using `OP_NOP3`, I was wondering if there were any plans to add support and tests.

**Comment by dcousens** [comment]
PR accepted to https://github.com/bitcoinjs/bitcoin-ops

100% we want this,  but haven't added it yet.

**Comment by afk11** [comment]
This is not an easy task.. All our templates to date are _static_ in terms of the opcodes used. But CSV is an opcode that is _never_ used by itself. I would say our biggest blocker to this is having to pivot from static templates, to dynamic templates. 

Eg: 
```
[height] CSV DUP HASH160 [hash] EQUALVERIFY CHECKSIG
```

This one is easy, and we could add a template.. Moreso however, it should be two templates: CSV || P2PKH. But most usages of CSV actually are inside IF ELSE ENDIF branches such as this: 
```
IF 
    [height] CSV DUP HASH160 [hash] EQUALVERIFY CHECKSIG
ELSE
    2-of-2 CHECKMULTISIG
ENDIF
```
Here the first script is inside an IF branch.. but what happens if we move the CSV part outside?
```
[height] CSV 
IF 
    DUP HASH160 [hash] EQUALVERIFY CHECKSIG
ELSE
    2-of-2 CHECKMULTISIG
ENDIF
```
Anyways, just generalizing here, this applies for CLTV, and others too, but it highlights the ground work needed..  The actual code for "signing" or "verifying" CSV isn't that much work. Just check the txins sequence >= CSV stack value. 

The bulk is in parsing out stack values, and it really becomes a mindfield.. 

It's not impossible, but dealing with these type of scripts _without_ resorting to a static list of templates made in bitcoinjs is quite tough!

**Comment by afk11** [comment]
This might be the first logical step towards this, and getting CSV support sooner rather than later..

* Deal with scripts with only execution pathway, with multiple templates, such as
    * 100 CSV [Alice] CHECKSIG
    * [Alice] CHECKSIG 100 CSV
    * DUP HASH160 [AliceHash] EQUALVERIFY CHECKSIG [Bob] CHECKSIG 2 [Carol] [Mallory] 3 CHECKMULTISIG
    * and so on

* Deal with scripts with multiple branches, and multiple templates.
    * IF [P2PKH] ELSE [multisig] ENDIF
    * DUP HASH160 [hash] EQUAL IF [P2PKH1] ELSE [P2PKH2]

**Comment by dabura667** [comment]
> but what happens if we move the CSV part outside?

@afk11 The OP_IF won't run at all because the CSV fails and OP_VERIFY contained in it fails.

personally I am against CSV templates....... There's just too many options for height values, and those height values need to be stored by the wallets adding complexity...

We could add templates for fixed CSV/CLTV values (144 blocks = 1 day) for 1 day, one week, one month...

Or we could change it so that the library only uses 144 block granularity and add a function that takes a P2SH address and a ECPair and brute forces to check how many days the address waits for...

otherwise I don't recommend it...

**Comment by dcousens** [comment]
@dabura667 I think CSV templates will be worthwhile,  but maybe not as part of this library to start.   Modules!

**Comment by afk11** [comment]
@dabura667 I'm aware - the point is you can have random IF's in the middle of your 'templates', so you do need to parse out mutually exclusive opcodes to see what the templates are.

And, I wouldn't suggest having a 144D_CSV_P2PK, and others intervals.. I'd just have the templating engine match several templates within a scriptPubKey.

For the heights.. those are embedded in the scriptPubKey/rs/ws, so you can check the transaction being signed satisfies it.

**Comment by dcousens** [comment]
Added BIP68 to README,  with intentions to add some BIP112 integration examples

**Comment by dcousens** [comment]
Closing in favour of https://github.com/bitcoinjs/bitcoinjs-lib/compare/csv?expand=1
