### ISSUE TITLE
How to calculate fees in segwit multi-sig

### ISSUE THREAD

**Issue by rbndg** [bitcoinjs/bitcoinjs-lib#977]
Hello

I'm doing a multi-sig transaction and i'm not sure how i should calculate the transaction fee.

I want 1 party to sign a tx and pass the transaction to another party to sign and then broadcast. 

If i understand this correctly, i need to call getVirtualSize to calculate the TX Fee, However the witness field isn't completed yet. Because i'm waiting for the other party to sign the tx

**Comment by dabura667** [comment]
https://gist.github.com/dabura667/1bb77d63d38bfd99a0ce453db74e0115

```javascript
// 2-of-3 multisig with 3 inputs sent to 2 P2PKH outputs.
getByteCount({'MULTISIG-P2SH-P2WSH:2-3': 3}, {'P2PKH': 2})
// 373 virtual Bytes (1/4 weight)
```

**Comment by dabura667** [comment]
remove P2SH- if you want to measure for native segwit

**Comment by dabura667** [comment]
This assumes compressed pubkeys in all cases.

It also assumes the S value is always 32 bytes length and the R value of each signature is always 33 bytes (with the 0x00 padding) so that we estimate the maximum possible size. This will create a maximum possible 1 weight (4 weight for non-segwit) variance per signature contained.

**Comment by dabura667** [comment]
Example:
https://www.smartbit.com.au/tx/c8e32240ed79baa07564b30216b9d148f41ef9141b96ff6ebb0e6dd08f49ac96

```javascript
getByteCount({'P2PKH': 77}, {'P2PKH': 2})
// 11474
```

but if you look at the API response by clicking the `</>` button, it says 11433... if we search the page for `"asm": "3045022100` (Which means the r value was 33 bytes for the input) we get 36 hits... 77 inputs - 36 == 41 inputs with a 32 byte r value...

11474 - 11433 == 41 exactly. So we overestimated by 41 bytes because there were 77 signatures and 53% of them were 32 byte r values. (s values are always 32 or less, because s values must be low-s due to recent standardness rules)

**Comment by dabura667** [comment]
@dcousens I wonder if there's a way we can include this function as a prototype for Transaction or TransactionBuilder..... hmmm....

**Comment by afk11** [comment]
@dabura667 I've been working on something on size estimation I was eventually going to push here https://github.com/blocktrail/blocktrail-sdk-nodejs/blob/master/lib/size_estimation.js It's a little heavier, but think it's pretty clear and avoids the magic numbers that many size estimators happen to have.

**Comment by dabura667** [comment]
my colleague made this a while back https://github.com/you21979/node-bitcoin-util-fee/blob/master/index.js

Doesn't support segwit... but it's very... verbose.

**Comment by sneurlax** [comment]
... very verbose.

**Comment by rbndg** [comment]
@afk11 does size_estimation.js allow estimation of P2SH-P2WSH ?

**Comment by junderw** [comment]
Yes it does.

**Comment by dcousens** [comment]
@dabura667 you should incorporate https://gist.github.com/dabura667/1bb77d63d38bfd99a0ce453db74e0115 into https://github.com/bitcoinjs/coinselect

**Comment by rbndg** [comment]
@junderw I don't believe it does, 
In the estimateUtxo function, the array of allowed script contains only:

`  var allowedTypes = [types.MULTISIG, types.P2PKH, types.P2PK]
`

However correct me if i'm wrong :)

**Comment by rbndg** [comment]
@dabura667 i'm going to use your gist, It's quiet handy and easy to understand

**Comment by tipu** [comment]
the gist is no longer available -- anyone know where one can access it or a similar resource ?

**Comment by afk11** [comment]
@rbndg it does support P2SH-P2WSH - the allowedTypes vars refer to the types of scripts which can be nested _inside_ a P2SH-P2WSH script

**Comment by junderw** [comment]
@tipu I have a copy on my gist: I'll replace the links.

https://gist.github.com/junderw/b43af3253ea5865ed52cb51c200ac19c
